#![deny(missing_docs)]
#![deny(rustdoc::broken_intra_doc_links)]

//! MongoDB persistence adapter for Lily applications.
//!
//! This crate owns the MongoDB client lifecycle, generates typed collection
//! adapters and optional repository adapters, and runs explicit versioned
//! migrations. Application controllers normally call a domain service. That
//! service may inject a type generated by [`MongoCollection`] and use its
//! public CRUD methods directly. Alternatively, it may inject the
//! `lily_mongo_repository::MongoRepository` implementation generated by
//! [`Repository`] when the common repository contract is useful. Neither path
//! is required by the other. [`DatabaseService::collection`] is the lower-level
//! driver escape hatch for operations outside the generated collection API.
//!
//! # Single-database mode
//!
//! The default `single` feature registers [`DatabaseService`] as a singleton.
//! It reads the validated `database` section from `lily_config`, connects and
//! performs a readiness ping during application startup. A collection injects
//! that service. A repository may optionally inject the collection:
//!
//! ```ignore
//! use std::sync::Arc;
//!
//! use lily_mongo_repository::{MongoFilter, MongoOperationContext};
//! use lily_injectable_derive::Injectable;
//! use lily_injection::ServiceTrait;
//! use lily_mongodb::{Collection, DatabaseService, MongoCollection, Repository};
//! use mongodb::bson::{doc, oid::ObjectId};
//! use serde::{Deserialize, Serialize};
//!
//! #[derive(Clone, Serialize, Deserialize)]
//! struct Application {
//!     #[serde(skip_serializing_if = "Option::is_none")]
//!     _id: Option<ObjectId>,
//!     name: String,
//! }
//!
//! #[derive(Injectable, MongoCollection, Default)]
//! #[collection("applications")]
//! #[collection_type(Application)]
//! #[service(lifetime = "Singleton")]
//! struct ApplicationCollection {
//!     #[inject]
//!     db: Arc<DatabaseService>,
//!     collection: Option<Collection<Application>>,
//! }
//!
//! // MongoCollection supplies ServiceTrait and public typed CRUD methods for
//! // the collection. A domain service may inject ApplicationCollection
//! // directly; the repository below is optional.
//!
//! #[derive(Injectable, Default)]
//! #[service(lifetime = "Singleton")]
//! struct ApplicationService {
//!     #[inject]
//!     collection: Arc<ApplicationCollection>,
//! }
//!
//! impl ServiceTrait for ApplicationService {}
//!
//! impl ApplicationService {
//!     async fn find_by_name(
//!         &self,
//!         name: &str,
//!     ) -> Result<Option<Application>, lily_mongo_repository::MongoRepositoryError> {
//!         let filter = MongoFilter::new(doc! { "name": name })?;
//!         let operation = MongoOperationContext::detached();
//!         self.collection.find_one(filter, &operation).await
//!     }
//! }
//!
//! #[derive(Injectable, Repository, Default)]
//! #[entity_type(Application)]
//! #[collection_type(ApplicationCollection)]
//! #[service(lifetime = "Singleton")]
//! struct ApplicationRepository {
//!     #[inject]
//!     collection: Arc<ApplicationCollection>,
//! }
//!
//! // Repository supplies the optional MongoRepository<Application> contract,
//! // not ServiceTrait.
//! impl ServiceTrait for ApplicationRepository {}
//! ```
//!
//! Do not manually implement `ServiceTrait` for a `MongoCollection` type: that
//! implementation is generated so it can acquire its lightweight driver
//! collection handle after the database dependency is ready.
//!
//! # Factory mode
//!
//! Applications requiring named database cells disable default features and
//! enable `factory`. `MongoFactory` is then the singleton owner. A collection
//! injects `Arc<MongoFactory>`, declares `#[cell_name("...")]`, and keeps
//! `db: Arc<DatabaseService>` as runtime state populated by the generated
//! lifecycle implementation. It must not mark that `db` field with `#[inject]`.
//!
//! ```toml
//! lily_mongodb = { version = "0.1", default-features = false, features = ["factory"] }
//! ```
//!
//! `single` and `factory` are mutually exclusive. When used, the optional
//! repository shape does not change between modes.
//!
//! # Migrations are explicit
//!
//! `MongoCollection` turns `#[index]`, `#[unique_field]` and
//! `#[unique_combination]` attributes into validated [`MongoMigrationStep`]
//! values. It never performs DDL during DI initialization. The deployment
//! composition root assigns a positive version with [`MongoMigration::new`]
//! and applies the ordered plan through [`MongoMigrationRunner`].
//! Framework-owned or independently versioned storage uses
//! [`MongoMigrationRunner::for_component`] so its migration versions and
//! distributed lease cannot collide with the application-default ledger.
//! For example, Lily's transactional queue adapter owns the validated
//! `lily.queue.transactional_inbox` namespace. Creating either runner still
//! performs no I/O or runtime DDL.
//!
//! # Operational boundaries
//!
//! Generated collection and repository CRUD operations require a
//! `MongoOperationContext` from
//! [`DatabaseService::operation_context`]. That context carries the configured
//! deadline and caller cancellation token; it may also carry a transaction and
//! optimistic-concurrency revision. Collection handles are cheap clones, while
//! the database service or factory remains the client lifecycle owner.
//! Before admitting transactional work, call
//! [`DatabaseService::verify_transaction_capability`]. Transactions started by
//! [`DatabaseService::begin_transaction`] use snapshot reads and
//! majority+journaled writes with a bounded commit time. Framework transaction
//! and migration lease authorities require MongoDB 4.2 or newer so update
//! pipelines can derive expiry timestamps from the database server clock.
//! Transaction owners can attach the hidden shared observation token to independently
//! created operation contexts; application code continues to use
//! `with_transaction`.
//!
//! The derive output is compiled in the application crate. Until Lily's
//! umbrella facade owns generated paths, downstream crates using these derives
//! must directly declare the crates named by the generated code. This is a
//! macro ABI constraint, not a second registration or lifecycle API.

#[cfg(all(feature = "single", feature = "factory"))]
compile_error!(
    "lily_mongodb features `single` and `factory` are mutually exclusive; disable default features before enabling `factory`"
);

extern crate self as lily_mongodb;

mod database;
mod lifecycle;
mod migration;
mod options;

#[cfg(feature = "factory-api")]
mod mongo_factory;

pub use database::DatabaseService;
pub use lifecycle::MongoShutdownHandle;
pub use migration::{
    MongoMigration, MongoMigrationReport, MongoMigrationRunner, MongoMigrationStep,
};
#[cfg(feature = "factory-api")]
#[cfg_attr(not(feature = "factory"), doc(hidden))]
pub use mongo_factory::MongoFactory;
pub use options::MongoClientPlan;

/// Error vocabulary returned by Lily's MongoDB connection boundary.
pub use lily_error::application::mongodb::MongoDbError;
pub use lily_mongodb_derive::{MongoCollection, Repository};

/// Typed MongoDB collection handle stored by `#[derive(MongoCollection)]`.
pub use mongodb::Collection;
/// BSON types and helpers used by MongoDB entity and migration definitions.
pub use mongodb::bson;
/// Driver collection metadata used by Lily's read-only readiness adapters.
#[doc(hidden)]
pub use mongodb::results::CollectionSpecification;

/// Trace macro/runtime path used by generated collection implementations.
#[doc(hidden)]
pub use lily_trace;
