[package]
name = "lily_queue_registry"
version = "0.1.0"
edition = "2024"
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[features]
default = []
asyncapi = ["dep:lily_asyncapi"]

[dependencies]
linkme = { workspace = true }
lily_error = { version = "0.1.0", path = "../../foundation/lily_error" }
lily_injection = { version = "0.1.0", path = "../../foundation/lily_injection" }
lily_asyncapi = { version = "=0.1.0", path = "../lily_asyncapi", optional = true }
