use crate::response::response_ext::ResponseBuilder;
use crate::{
    BodyBudget, BodyBudgetError, CookieKeyRing, CookieRemoval, ResponseCookie, ResponseCookieError,
};

use bytes::Bytes;
use futures::Stream;
use http::{HeaderName, HeaderValue};
use lily_error::application::http_api::HttpApiError;
use smallvec::SmallVec;
use std::{
    convert::Infallible,
    pin::Pin,
    task::{Context, Poll},
};
use zeroize::Zeroize;

/// Default number of application response header field lines.
///
/// Repeated `Set-Cookie` fields count individually. Transport-owned fields,
/// such as generated `Content-Length` and `Server`, are outside this
/// application-level limit and cannot be inserted through [`Response`].
pub const DEFAULT_MAX_RESPONSE_HEADERS: usize = 64;

/// Default aggregate wire bytes for application response header field lines.
///
/// Accounting includes each field's name, `: ` separator, value, and trailing
/// CRLF. The final empty line and transport-owned fields are not included.
pub const DEFAULT_MAX_RESPONSE_HEADER_BYTES: usize = 64 * 1024;

/// Framework safety ceiling for configured application response headers.
pub const HARD_MAX_RESPONSE_HEADERS: usize = 1024;

/// Framework safety ceiling for retained application response header bytes.
pub const HARD_MAX_RESPONSE_HEADER_BYTES: usize = 1024 * 1024;

const INLINE_RESPONSE_HEADERS: usize = 8;

/// A fail-closed response-header mutation error.
///
/// Neither this error's `Debug` nor `Display` output contains caller-provided
/// header names or values, because either may carry sensitive data.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
#[non_exhaustive]
pub enum ResponseHeaderError {
    /// The field name is not a valid HTTP header name.
    #[error("response header name is invalid")]
    InvalidName,
    /// The field value contains bytes forbidden by the HTTP grammar.
    #[error("response header value is invalid")]
    InvalidValue,
    #[error("response header count exceeds the configured limit of {limit}")]
    /// Adding the field would exceed the effective field-line count.
    TooManyHeaders {
        /// Effective maximum field-line count.
        limit: usize,
    },
    /// Adding the field would exceed the effective aggregate wire-byte limit.
    #[error("response header bytes exceed the configured limit of {limit_bytes}")]
    HeadersTooLarge {
        /// Effective maximum aggregate wire bytes.
        limit_bytes: usize,
    },
    /// The field is a singleton and was already present.
    #[error("response header does not permit duplicate field lines")]
    DuplicateSingleton,
    /// The field is generated by Lily's transport rather than applications.
    #[error("response header is controlled by the HTTP transport")]
    TransportControlled,
    /// Hop-by-hop fields cannot be forwarded through an application response.
    #[error("hop-by-hop response headers are not accepted from applications")]
    HopByHop,
}

/// A typed, secret-safe failure while writing or deleting a response cookie.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
#[non_exhaustive]
pub enum ResponseCookieWriteError {
    /// Cookie construction or serialization failed.
    #[error(transparent)]
    Cookie(#[from] ResponseCookieError),
    /// Inserting the serialized `Set-Cookie` field failed.
    #[error(transparent)]
    Header(#[from] ResponseHeaderError),
}

impl From<ResponseCookieWriteError> for HttpApiError {
    fn from(error: ResponseCookieWriteError) -> Self {
        HttpApiError::ResponseEncodingError(error.to_string())
    }
}

/// A stable, payload-free buffered or streaming response-body failure.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
#[non_exhaustive]
pub enum ResponseBodyError {
    /// A buffered body exceeded its effective byte budget.
    #[error("response body exceeds the configured {limit_bytes}-byte limit")]
    LimitExceeded {
        /// Effective body limit.
        limit_bytes: usize,
    },
    /// Body-length arithmetic overflowed.
    #[error("response body length overflowed the configured {limit_bytes}-byte limit")]
    LengthOverflow {
        /// Effective body limit.
        limit_bytes: usize,
    },
    /// Allocation failed before exceeding the configured bound.
    #[error("response body allocation failed within the configured {limit_bytes}-byte limit")]
    AllocationFailed {
        /// Effective body limit.
        limit_bytes: usize,
    },
    /// Buffered and streaming writers were selected for the same response.
    #[error("buffered and streaming response body modes cannot be mixed")]
    BodyModeConflict,
    /// The configured per-chunk limit is zero.
    #[error("response stream chunk limit must be greater than zero")]
    InvalidStreamChunkLimit,
    /// The configured cumulative stream limit is zero.
    #[error("response stream cumulative limit must be greater than zero when configured")]
    InvalidStreamTotalLimit,
    #[error(
        "response stream produced a chunk larger than the configured {limit_bytes}-byte limit"
    )]
    /// A source emitted a chunk larger than the effective per-chunk limit.
    StreamChunkTooLarge {
        /// Effective per-chunk limit.
        limit_bytes: usize,
    },
    /// Cumulative emitted bytes exceeded the effective stream limit.
    #[error("response stream exceeded the configured {limit_bytes}-byte cumulative limit")]
    StreamLimitExceeded {
        /// Effective cumulative stream limit.
        limit_bytes: u64,
    },
    /// Emitted bytes exceeded the stream's declared exact length.
    #[error("response stream exceeded its declared {expected_bytes}-byte length")]
    StreamLengthExceeded {
        /// Declared exact length.
        expected_bytes: u64,
    },
    /// The stream ended before its declared exact length.
    #[error(
        "response stream ended after {actual_bytes} bytes instead of its declared {expected_bytes} bytes"
    )]
    StreamLengthIncomplete {
        /// Declared exact length.
        expected_bytes: u64,
        /// Bytes emitted before the stream ended.
        actual_bytes: u64,
    },
    /// The application stream returned an error whose payload is deliberately discarded.
    #[error("response stream source failed")]
    StreamSourceFailed,
    /// The retained HTTP producer was stopped before completion.
    #[error("response stream was interrupted")]
    StreamInterrupted,
}

impl ResponseBodyError {
    /// Stable, payload-free diagnostic code used after response headers commit.
    #[must_use]
    pub const fn error_code(self) -> &'static str {
        match self {
            Self::LimitExceeded { .. } => "RESPONSE_BODY_LIMIT_EXCEEDED",
            Self::LengthOverflow { .. } => "RESPONSE_BODY_LENGTH_OVERFLOW",
            Self::AllocationFailed { .. } => "RESPONSE_BODY_ALLOCATION_FAILED",
            Self::BodyModeConflict => "RESPONSE_BODY_MODE_CONFLICT",
            Self::InvalidStreamChunkLimit => "RESPONSE_STREAM_CHUNK_LIMIT_INVALID",
            Self::InvalidStreamTotalLimit => "RESPONSE_STREAM_TOTAL_LIMIT_INVALID",
            Self::StreamChunkTooLarge { .. } => "RESPONSE_STREAM_CHUNK_TOO_LARGE",
            Self::StreamLimitExceeded { .. } => "RESPONSE_STREAM_LIMIT_EXCEEDED",
            Self::StreamLengthExceeded { .. } => "RESPONSE_STREAM_LENGTH_EXCEEDED",
            Self::StreamLengthIncomplete { .. } => "RESPONSE_STREAM_LENGTH_INCOMPLETE",
            Self::StreamSourceFailed => "RESPONSE_STREAM_SOURCE_FAILED",
            Self::StreamInterrupted => "RESPONSE_STREAM_INTERRUPTED",
        }
    }
}

impl From<Infallible> for ResponseBodyError {
    fn from(error: Infallible) -> Self {
        match error {}
    }
}

impl From<std::io::Error> for ResponseBodyError {
    /// Maps an application I/O source failure without retaining its potentially
    /// sensitive path, endpoint, or operating-system message.
    fn from(_error: std::io::Error) -> Self {
        Self::StreamSourceFailed
    }
}

impl From<BodyBudgetError> for ResponseBodyError {
    fn from(error: BodyBudgetError) -> Self {
        match error {
            BodyBudgetError::LimitExceeded { limit_bytes } => Self::LimitExceeded { limit_bytes },
            BodyBudgetError::LengthOverflow { limit_bytes } => Self::LengthOverflow { limit_bytes },
            BodyBudgetError::InvalidLimit { limit_bytes, .. } => {
                Self::LimitExceeded { limit_bytes }
            }
        }
    }
}

impl From<ResponseBodyError> for HttpApiError {
    fn from(error: ResponseBodyError) -> Self {
        HttpApiError::ResponseEncodingError(error.to_string())
    }
}

/// A failure to construct an HTTP response, separate from an application error
/// that can itself be successfully converted into a response.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
#[non_exhaustive]
pub enum ResponseWriteError {
    /// A response header mutation failed.
    #[error(transparent)]
    Header(#[from] ResponseHeaderError),
    /// A response body mutation failed.
    #[error(transparent)]
    Body(#[from] ResponseBodyError),
    /// JSON serialization failed without a more specific body-policy failure.
    #[error("response JSON serialization failed")]
    Serialization,
    /// Staged response metadata could not be committed.
    #[error(transparent)]
    Passthrough(#[from] super::response_ext::PassthroughResponseError),
    /// A converter did not fulfill the response mode's materialization contract.
    #[error("response conversion returned an invalid outcome")]
    InvalidOutcome,
}

impl From<ResponseWriteError> for HttpApiError {
    fn from(error: ResponseWriteError) -> Self {
        HttpApiError::ResponseEncodingError(error.to_string())
    }
}

/// Validated limits copied from one effective HTTP server snapshot.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ResponseLimits {
    body_budget: BodyBudget,
    max_header_count: usize,
    max_header_bytes: usize,
    streaming: ResponseStreamingLimits,
}

/// Validated response-streaming limits copied from one effective server snapshot.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ResponseStreamingLimits {
    max_chunk_bytes: usize,
    max_total_bytes: Option<u64>,
}

impl ResponseStreamingLimits {
    /// Validates a per-chunk limit and optional cumulative stream limit.
    pub const fn new(
        max_chunk_bytes: usize,
        max_total_bytes: Option<u64>,
    ) -> Result<Self, ResponseLimitsError> {
        if max_chunk_bytes == 0 || max_chunk_bytes > crate::MAX_BODY_LIMIT_BYTES {
            return Err(ResponseLimitsError::InvalidStreamChunkBytes {
                configured: max_chunk_bytes,
                maximum: crate::MAX_BODY_LIMIT_BYTES,
            });
        }
        if matches!(max_total_bytes, Some(0)) {
            return Err(ResponseLimitsError::InvalidStreamTotalBytes);
        }
        Ok(Self {
            max_chunk_bytes,
            max_total_bytes,
        })
    }

    #[must_use]
    /// Returns the effective per-chunk byte limit.
    pub const fn max_chunk_bytes(self) -> usize {
        self.max_chunk_bytes
    }

    #[must_use]
    /// Returns the optional cumulative stream byte limit.
    pub const fn max_total_bytes(self) -> Option<u64> {
        self.max_total_bytes
    }
}

impl Default for ResponseStreamingLimits {
    fn default() -> Self {
        Self {
            max_chunk_bytes: 64 * 1024,
            max_total_bytes: None,
        }
    }
}

impl ResponseLimits {
    /// Validates buffered-body and application-header limits.
    pub const fn new(
        body_budget: BodyBudget,
        max_header_count: usize,
        max_header_bytes: usize,
    ) -> Result<Self, ResponseLimitsError> {
        if max_header_count == 0 || max_header_count > HARD_MAX_RESPONSE_HEADERS {
            return Err(ResponseLimitsError::InvalidHeaderCount {
                configured: max_header_count,
                maximum: HARD_MAX_RESPONSE_HEADERS,
            });
        }
        if max_header_bytes == 0 || max_header_bytes > HARD_MAX_RESPONSE_HEADER_BYTES {
            return Err(ResponseLimitsError::InvalidHeaderBytes {
                configured: max_header_bytes,
                maximum: HARD_MAX_RESPONSE_HEADER_BYTES,
            });
        }
        Ok(Self {
            body_budget,
            max_header_count,
            max_header_bytes,
            streaming: ResponseStreamingLimits {
                max_chunk_bytes: 64 * 1024,
                max_total_bytes: None,
            },
        })
    }

    /// Replaces the streaming limits in this immutable effective snapshot.
    pub const fn with_streaming_limits(mut self, streaming: ResponseStreamingLimits) -> Self {
        self.streaming = streaming;
        self
    }

    #[must_use]
    /// Returns the buffered response body budget.
    pub const fn body_budget(self) -> BodyBudget {
        self.body_budget
    }

    #[must_use]
    /// Returns the maximum application header field-line count.
    pub const fn max_header_count(self) -> usize {
        self.max_header_count
    }

    #[must_use]
    /// Returns the maximum aggregate application header wire bytes.
    pub const fn max_header_bytes(self) -> usize {
        self.max_header_bytes
    }

    #[must_use]
    /// Returns the response-streaming limits.
    pub const fn streaming(self) -> ResponseStreamingLimits {
        self.streaming
    }
}

impl Default for ResponseLimits {
    fn default() -> Self {
        Self {
            body_budget: BodyBudget::default(),
            max_header_count: DEFAULT_MAX_RESPONSE_HEADERS,
            max_header_bytes: DEFAULT_MAX_RESPONSE_HEADER_BYTES,
            streaming: ResponseStreamingLimits::default(),
        }
    }
}

/// Invalid effective response-limit configuration.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
#[non_exhaustive]
pub enum ResponseLimitsError {
    /// Header count is zero or exceeds the framework ceiling.
    #[error("response header count {configured} is outside 1..={maximum}")]
    InvalidHeaderCount {
        /// Rejected value.
        configured: usize,
        /// Framework ceiling.
        maximum: usize,
    },
    /// Aggregate header bytes are zero or exceed the framework ceiling.
    #[error("response header bytes {configured} is outside 1..={maximum}")]
    InvalidHeaderBytes {
        /// Rejected value.
        configured: usize,
        /// Framework ceiling.
        maximum: usize,
    },
    /// Stream chunk bytes are zero or exceed the body ceiling.
    #[error("response stream chunk bytes {configured} is outside 1..={maximum}")]
    InvalidStreamChunkBytes {
        /// Rejected value.
        configured: usize,
        /// Framework ceiling.
        maximum: usize,
    },
    /// A configured cumulative stream limit was zero.
    #[error("response stream cumulative byte limit must be greater than zero when configured")]
    InvalidStreamTotalBytes,
}

struct StoredHeader {
    name: HeaderName,
    value: HeaderValue,
    wire_bytes: usize,
}

/// Mutable response state owned by one HTTP request.
///
/// Most actions return an [`crate::IntoResponse`] value. Raw access is
/// available for actions that intentionally own the complete response.
pub struct Response {
    headers: SmallVec<[StoredHeader; INLINE_RESPONSE_HEADERS]>,
    header_bytes: usize,
    status_message: StatusMessage,
    limits: ResponseLimits,
    body: ResponseBody,
}

enum ResponseBody {
    Full(BufferedResponseBody),
    Stream(ResponseBodyStream),
}

impl ResponseBody {
    fn full_mut(&mut self) -> Result<&mut BufferedResponseBody, ResponseBodyError> {
        match self {
            Self::Full(body) => Ok(body),
            Self::Stream(_) => Err(ResponseBodyError::BodyModeConflict),
        }
    }

    fn first_failure(&self) -> Option<ResponseBodyError> {
        match self {
            Self::Full(body) => body.first_failure(),
            Self::Stream(_) => None,
        }
    }
}

/// Type-erased, fallible application response stream plus its effective policy.
///
/// Applications construct this through [`crate::streaming`]. HTTP transports
/// poll it lazily after action and middleware execution have completed.
#[doc(hidden)]
pub struct ResponseBodyStream {
    inner: Pin<Box<dyn ErasedResponseStream>>,
}

impl std::fmt::Debug for ResponseBodyStream {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("ResponseBodyStream")
            .field("exact_length", &self.exact_length())
            .field("max_chunk_bytes", &self.max_chunk_bytes())
            .field("max_total_bytes", &self.max_total_bytes())
            .finish_non_exhaustive()
    }
}

impl ResponseBodyStream {
    pub(crate) fn new<S>(source: S) -> Self
    where
        S: Stream<Item = Result<Bytes, ResponseBodyError>> + Send + 'static,
    {
        Self {
            inner: Box::pin(ErasedResponseStreamState::new(source)),
        }
    }

    pub(crate) fn set_exact_length(&mut self, exact_length: Option<u64>) {
        self.inner.as_mut().set_exact_length(exact_length);
    }

    pub(crate) fn set_max_chunk_bytes(&mut self, max_chunk_bytes: Option<usize>) {
        if let Some(max_chunk_bytes) = max_chunk_bytes {
            self.inner.as_mut().set_max_chunk_bytes(max_chunk_bytes);
        }
    }

    pub(crate) fn set_max_total_bytes(&mut self, max_total_bytes: Option<u64>) {
        self.inner.as_mut().set_max_total_bytes(max_total_bytes);
    }

    fn apply_server_limits(&mut self, limits: ResponseStreamingLimits) {
        self.inner.as_mut().apply_server_limits(limits);
    }

    #[must_use]
    pub fn exact_length(&self) -> Option<u64> {
        self.inner.as_ref().get_ref().exact_length()
    }

    #[must_use]
    pub fn max_chunk_bytes(&self) -> usize {
        self.inner.as_ref().get_ref().max_chunk_bytes()
    }

    #[must_use]
    pub fn max_total_bytes(&self) -> Option<u64> {
        self.inner.as_ref().get_ref().max_total_bytes()
    }

    #[must_use]
    pub fn emitted_bytes(&self) -> u64 {
        self.inner.as_ref().get_ref().emitted_bytes()
    }

    /// Polls at most one transport-sized chunk while enforcing the stream's
    /// source-chunk, cumulative, and exact-length contracts.
    #[doc(hidden)]
    pub fn poll_bounded_chunk(
        mut self: Pin<&mut Self>,
        context: &mut Context<'_>,
        max_frame_bytes: usize,
    ) -> Poll<Option<Result<Bytes, ResponseBodyError>>> {
        self.inner
            .as_mut()
            .poll_bounded_chunk(context, max_frame_bytes.max(1))
    }
}

impl Stream for ResponseBodyStream {
    type Item = Result<Bytes, ResponseBodyError>;

    fn poll_next(mut self: Pin<&mut Self>, context: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        self.as_mut().poll_bounded_chunk(context, usize::MAX)
    }
}

trait ErasedResponseStream: Send {
    fn set_exact_length(self: Pin<&mut Self>, exact_length: Option<u64>);
    fn set_max_chunk_bytes(self: Pin<&mut Self>, max_chunk_bytes: usize);
    fn set_max_total_bytes(self: Pin<&mut Self>, max_total_bytes: Option<u64>);
    fn apply_server_limits(self: Pin<&mut Self>, limits: ResponseStreamingLimits);
    fn exact_length(&self) -> Option<u64>;
    fn max_chunk_bytes(&self) -> usize;
    fn max_total_bytes(&self) -> Option<u64>;
    fn emitted_bytes(&self) -> u64;
    fn poll_bounded_chunk(
        self: Pin<&mut Self>,
        context: &mut Context<'_>,
        max_frame_bytes: usize,
    ) -> Poll<Option<Result<Bytes, ResponseBodyError>>>;
}

pin_project_lite::pin_project! {
    struct ErasedResponseStreamState<S> {
        #[pin]
        source: S,
        exact_length: Option<u64>,
        max_chunk_bytes: usize,
        max_total_bytes: Option<u64>,
        pending: Bytes,
        accepted_bytes: u64,
        emitted_bytes: u64,
        terminal: bool,
    }
}

impl<S> ErasedResponseStreamState<S> {
    fn new(source: S) -> Self {
        Self {
            source,
            exact_length: None,
            max_chunk_bytes: usize::MAX,
            max_total_bytes: None,
            pending: Bytes::new(),
            accepted_bytes: 0,
            emitted_bytes: 0,
            terminal: false,
        }
    }
}

impl<S> ErasedResponseStream for ErasedResponseStreamState<S>
where
    S: Stream<Item = Result<Bytes, ResponseBodyError>> + Send + 'static,
{
    fn set_exact_length(self: Pin<&mut Self>, exact_length: Option<u64>) {
        *self.project().exact_length = exact_length;
    }

    fn set_max_chunk_bytes(self: Pin<&mut Self>, max_chunk_bytes: usize) {
        *self.project().max_chunk_bytes = max_chunk_bytes;
    }

    fn set_max_total_bytes(self: Pin<&mut Self>, max_total_bytes: Option<u64>) {
        *self.project().max_total_bytes = max_total_bytes;
    }

    fn apply_server_limits(self: Pin<&mut Self>, limits: ResponseStreamingLimits) {
        let this = self.project();
        *this.max_chunk_bytes = (*this.max_chunk_bytes).min(limits.max_chunk_bytes());
        *this.max_total_bytes =
            narrow_optional_limit(*this.max_total_bytes, limits.max_total_bytes());
    }

    fn exact_length(&self) -> Option<u64> {
        self.exact_length
    }

    fn max_chunk_bytes(&self) -> usize {
        self.max_chunk_bytes
    }

    fn max_total_bytes(&self) -> Option<u64> {
        self.max_total_bytes
    }

    fn emitted_bytes(&self) -> u64 {
        self.emitted_bytes
    }

    fn poll_bounded_chunk(
        self: Pin<&mut Self>,
        context: &mut Context<'_>,
        max_frame_bytes: usize,
    ) -> Poll<Option<Result<Bytes, ResponseBodyError>>> {
        const MAX_EMPTY_CHUNKS_PER_POLL: usize = 16;
        let mut this = self.project();
        if *this.terminal {
            return Poll::Ready(None);
        }

        let mut empty_chunks = 0usize;
        loop {
            if !this.pending.is_empty() {
                let length = this.pending.len().min(max_frame_bytes);
                let frame = this.pending.split_to(length);
                *this.emitted_bytes = this.emitted_bytes.saturating_add(length as u64);
                return Poll::Ready(Some(Ok(frame)));
            }

            match this.source.as_mut().poll_next(context) {
                Poll::Pending => return Poll::Pending,
                Poll::Ready(Some(Ok(chunk))) if chunk.is_empty() => {
                    empty_chunks += 1;
                    if empty_chunks == MAX_EMPTY_CHUNKS_PER_POLL {
                        context.waker().wake_by_ref();
                        return Poll::Pending;
                    }
                }
                Poll::Ready(Some(Ok(chunk))) => {
                    if chunk.len() > *this.max_chunk_bytes {
                        *this.terminal = true;
                        return Poll::Ready(Some(Err(ResponseBodyError::StreamChunkTooLarge {
                            limit_bytes: *this.max_chunk_bytes,
                        })));
                    }
                    let chunk_bytes = u64::try_from(chunk.len()).unwrap_or(u64::MAX);
                    let next = match this.accepted_bytes.checked_add(chunk_bytes) {
                        Some(next) => next,
                        None => {
                            *this.terminal = true;
                            return Poll::Ready(Some(Err(
                                ResponseBodyError::StreamLimitExceeded {
                                    limit_bytes: this.max_total_bytes.unwrap_or(u64::MAX),
                                },
                            )));
                        }
                    };
                    if let Some(limit_bytes) = *this.max_total_bytes {
                        if next > limit_bytes {
                            *this.terminal = true;
                            return Poll::Ready(Some(Err(
                                ResponseBodyError::StreamLimitExceeded { limit_bytes },
                            )));
                        }
                    }
                    if let Some(expected_bytes) = *this.exact_length {
                        if next > expected_bytes {
                            *this.terminal = true;
                            return Poll::Ready(Some(Err(
                                ResponseBodyError::StreamLengthExceeded { expected_bytes },
                            )));
                        }
                    }
                    *this.accepted_bytes = next;
                    *this.pending = chunk;
                }
                Poll::Ready(Some(Err(error))) => {
                    *this.terminal = true;
                    return Poll::Ready(Some(Err(error)));
                }
                Poll::Ready(None) => {
                    *this.terminal = true;
                    if let Some(expected_bytes) = *this.exact_length {
                        if *this.accepted_bytes != expected_bytes {
                            return Poll::Ready(Some(Err(
                                ResponseBodyError::StreamLengthIncomplete {
                                    expected_bytes,
                                    actual_bytes: *this.accepted_bytes,
                                },
                            )));
                        }
                    }
                    return Poll::Ready(None);
                }
            }
        }
    }
}

const fn narrow_optional_limit(left: Option<u64>, right: Option<u64>) -> Option<u64> {
    match (left, right) {
        (Some(left), Some(right)) => Some(if left < right { left } else { right }),
        (Some(value), None) | (None, Some(value)) => Some(value),
        (None, None) => None,
    }
}

struct BufferedResponseBody {
    budget: BodyBudget,
    data: Vec<u8>,
    failure: Option<ResponseBodyError>,
}

impl BufferedResponseBody {
    fn new(budget: BodyBudget) -> Self {
        Self {
            budget,
            data: Vec::new(),
            failure: None,
        }
    }

    fn first_failure(&self) -> Option<ResponseBodyError> {
        self.failure
    }

    fn poison(&mut self, error: ResponseBodyError) -> ResponseBodyError {
        self.data.zeroize();
        self.data.clear();
        *self.failure.get_or_insert(error)
    }

    fn ensure_writable(&self) -> Result<(), ResponseBodyError> {
        self.failure.map_or(Ok(()), Err)
    }

    fn try_replace_vec(&mut self, data: Vec<u8>) -> Result<(), ResponseBodyError> {
        self.ensure_writable()?;
        if let Err(error) = self.budget.ensure_length(data.len()) {
            return Err(self.poison(error.into()));
        }
        self.data.zeroize();
        self.data = data;
        Ok(())
    }

    fn try_replace_slice(&mut self, data: &[u8]) -> Result<(), ResponseBodyError> {
        self.ensure_writable()?;
        if let Err(error) = self.budget.ensure_length(data.len()) {
            return Err(self.poison(error.into()));
        }
        let mut replacement = Vec::new();
        if replacement.try_reserve_exact(data.len()).is_err() {
            return Err(self.poison(ResponseBodyError::AllocationFailed {
                limit_bytes: self.budget.limit_bytes(),
            }));
        }
        replacement.extend_from_slice(data);
        self.data.zeroize();
        self.data = replacement;
        Ok(())
    }

    fn try_extend_from_slice(&mut self, data: &[u8]) -> Result<(), ResponseBodyError> {
        self.ensure_writable()?;
        if let Err(error) = self.budget.checked_next_length(self.data.len(), data.len()) {
            return Err(self.poison(error.into()));
        }
        if self.data.try_reserve_exact(data.len()).is_err() {
            return Err(self.poison(ResponseBodyError::AllocationFailed {
                limit_bytes: self.budget.limit_bytes(),
            }));
        }
        self.data.extend_from_slice(data);
        Ok(())
    }

    fn into_bytes(mut self) -> Result<Bytes, ResponseBodyError> {
        if let Some(error) = self.failure {
            return Err(error);
        }
        Ok(Bytes::from(std::mem::take(&mut self.data)))
    }
}

impl Drop for BufferedResponseBody {
    fn drop(&mut self) {
        self.data.zeroize();
    }
}

/// Allocation-aware serializer target. It is crate-private because response
/// converters, not application handlers, own serialization policy.
pub(crate) struct BoundedBodyWriter {
    body: BufferedResponseBody,
}

impl BoundedBodyWriter {
    pub(crate) fn new(budget: BodyBudget) -> Self {
        Self {
            body: BufferedResponseBody::new(budget),
        }
    }

    pub(crate) fn failure(&self) -> Option<ResponseBodyError> {
        self.body.first_failure()
    }

    pub(crate) fn finish(mut self) -> Result<Vec<u8>, ResponseBodyError> {
        self.body.ensure_writable()?;
        Ok(std::mem::take(&mut self.body.data))
    }
}

impl std::io::Write for BoundedBodyWriter {
    fn write(&mut self, bytes: &[u8]) -> std::io::Result<usize> {
        self.body
            .try_extend_from_slice(bytes)
            .map_err(|error| std::io::Error::other(error.to_string()))?;
        Ok(bytes.len())
    }

    fn flush(&mut self) -> std::io::Result<()> {
        Ok(())
    }
}

struct StatusMessage {
    code: usize,
    msg: &'static str,
}

/// Protocol-neutral response snapshot consumed by HTTP transport adapters.
#[derive(Debug)]
#[doc(hidden)]
pub struct TransportResponseParts {
    pub status: u16,
    pub headers: Vec<(String, String)>,
    /// Retains the established buffered transport snapshot for non-streaming responses.
    pub body: Bytes,
    /// Present only when the closed application body model selected streaming.
    pub stream: Option<ResponseBodyStream>,
}

impl TransportResponseParts {
    #[must_use]
    pub fn exact_length(&self) -> Option<u64> {
        self.stream.as_ref().map_or_else(
            || Some(self.body.len() as u64),
            ResponseBodyStream::exact_length,
        )
    }

    #[must_use]
    pub fn into_body(self) -> TransportResponseBody {
        self.stream.map_or_else(
            || TransportResponseBody::Full(self.body),
            TransportResponseBody::Stream,
        )
    }
}

/// Protocol-neutral body selected by the application response boundary.
#[doc(hidden)]
#[derive(Debug)]
pub enum TransportResponseBody {
    Full(Bytes),
    Stream(ResponseBodyStream),
}

impl Default for TransportResponseBody {
    fn default() -> Self {
        Self::Full(Bytes::new())
    }
}

impl From<Bytes> for TransportResponseBody {
    fn from(body: Bytes) -> Self {
        Self::Full(body)
    }
}

impl TransportResponseBody {
    #[must_use]
    pub fn exact_length(&self) -> Option<u64> {
        match self {
            Self::Full(body) => Some(body.len() as u64),
            Self::Stream(body) => body.exact_length(),
        }
    }

    #[must_use]
    pub const fn is_streaming(&self) -> bool {
        matches!(self, Self::Stream(_))
    }

    /// Returns the buffered representation length without treating an exact
    /// streaming declaration as bytes already observed by transport.
    #[must_use]
    pub const fn buffered_length(&self) -> Option<usize> {
        match self {
            Self::Full(body) => Some(body.len()),
            Self::Stream(_) => None,
        }
    }

    #[must_use]
    pub fn empty() -> Self {
        Self::Full(Bytes::new())
    }
}

impl Response {
    /// Creates a new response builder.
    pub fn builder() -> ResponseBuilder {
        ResponseBuilder::new()
    }

    /// Creates an empty `200 OK` response with default limits.
    pub async fn new() -> Result<Self, HttpApiError> {
        Self::with_limits(ResponseLimits::default()).await
    }

    /// Creates a response from one immutable effective limit snapshot.
    pub async fn with_limits(limits: ResponseLimits) -> Result<Self, HttpApiError> {
        Ok(Self::from_limits(limits))
    }

    /// Creates an empty response without performing any fallible work.
    #[must_use]
    pub fn from_limits(limits: ResponseLimits) -> Self {
        Self {
            headers: SmallVec::new(),
            header_bytes: 0,
            status_message: StatusMessage {
                code: 200,
                msg: "OK",
            },
            limits,
            body: ResponseBody::Full(BufferedResponseBody::new(limits.body_budget())),
        }
    }

    #[must_use]
    /// Returns the immutable effective response limits.
    pub const fn limits(&self) -> ResponseLimits {
        self.limits
    }

    #[must_use]
    /// Returns the effective buffered-body budget.
    pub const fn body_budget(&self) -> BodyBudget {
        self.limits.body_budget()
    }

    /// Returns the response's current HTTP status code.
    #[inline]
    pub fn status_code_value(&self) -> u16 {
        self.status_message.code as u16
    }

    /// Sets the status code.
    pub fn status(&mut self, code: u16, reason: &'static str) -> &mut Self {
        self.status_message.code = code as usize;
        self.status_message.msg = reason;
        self
    }

    /// Sets a static text body and its authoritative content type.
    pub fn text(&mut self, text: &'static str) -> Result<&mut Self, ResponseWriteError> {
        self.try_insert_header("Content-Type", "text/plain")?;
        self.body.full_mut()?.try_replace_slice(text.as_bytes())?;
        Ok(self)
    }

    /// Sets a body from an owned byte vector.
    pub fn set_body_vec(&mut self, data: Vec<u8>) -> Result<&mut Self, ResponseBodyError> {
        self.body.full_mut()?.try_replace_vec(data)?;
        Ok(self)
    }

    #[inline]
    /// Sets status metadata for Lily's application and middleware runtime.
    #[doc(hidden)]
    pub fn status_code(&mut self, code: usize, msg: &'static str) -> &mut Self {
        self.status_message = StatusMessage { code, msg };
        self
    }

    /// Atomically replaces the complete buffered application response.
    ///
    /// All headers are parsed and bounded before any existing status, header,
    /// or body state is changed. Response converters use this as their single
    /// terminal commit point so a failed conversion cannot leave a partial
    /// success response behind.
    pub(super) fn replace_buffered<'a, I>(
        &mut self,
        status: u16,
        reason: &'static str,
        headers: I,
        body: Vec<u8>,
    ) -> Result<(), ResponseWriteError>
    where
        I: IntoIterator<Item = (&'a str, &'a str)>,
    {
        if let Err(error) = self.limits.body_budget().ensure_length(body.len()) {
            let error = ResponseBodyError::from(error);
            if let Ok(current) = self.body.full_mut() {
                current.poison(error);
            }
            return Err(error.into());
        }
        if let ResponseBody::Full(current) = &self.body {
            current.ensure_writable()?;
        }
        let (prepared_headers, prepared_header_bytes) = prepare_headers(self.limits, headers)?;
        let mut replacement = BufferedResponseBody::new(self.limits.body_budget());
        replacement.try_replace_vec(body)?;

        self.headers = prepared_headers;
        self.header_bytes = prepared_header_bytes;
        self.status_message = StatusMessage {
            code: usize::from(status),
            msg: reason,
        };
        self.body = ResponseBody::Full(replacement);
        Ok(())
    }

    /// Atomically replaces the complete response with one lazy stream.
    pub(super) fn replace_streaming<'a, I>(
        &mut self,
        status: u16,
        reason: &'static str,
        headers: I,
        mut body: ResponseBodyStream,
    ) -> Result<(), ResponseWriteError>
    where
        I: IntoIterator<Item = (&'a str, &'a str)>,
    {
        if let ResponseBody::Full(current) = &self.body {
            current.ensure_writable()?;
        }
        if body.max_chunk_bytes() == 0 {
            return Err(ResponseBodyError::InvalidStreamChunkLimit.into());
        }
        if matches!(body.max_total_bytes(), Some(0)) {
            return Err(ResponseBodyError::InvalidStreamTotalLimit.into());
        }
        body.apply_server_limits(self.limits.streaming());
        if body
            .exact_length()
            .zip(body.max_total_bytes())
            .is_some_and(|(exact, maximum)| exact > maximum)
        {
            return Err(ResponseBodyError::StreamLimitExceeded {
                limit_bytes: body.max_total_bytes().expect("checked optional limit"),
            }
            .into());
        }
        let (prepared_headers, prepared_header_bytes) = prepare_headers(self.limits, headers)?;

        self.headers = prepared_headers;
        self.header_bytes = prepared_header_bytes;
        self.status_message = StatusMessage {
            code: usize::from(status),
            msg: reason,
        };
        self.body = ResponseBody::Stream(body);
        Ok(())
    }

    /// Appends one typed, validated `Set-Cookie` field line.
    #[inline]
    pub fn set_cookie(
        &mut self,
        cookie: &ResponseCookie,
    ) -> Result<&mut Self, ResponseCookieWriteError> {
        let value = cookie.to_header_value()?;
        self.try_append_header("Set-Cookie", &value)
            .map_err(ResponseCookieWriteError::from)
    }

    /// Appends one typed cookie signed with the key ring's primary key.
    #[inline]
    pub fn set_signed_cookie(
        &mut self,
        cookie: &ResponseCookie,
        key_ring: &CookieKeyRing,
    ) -> Result<&mut Self, ResponseCookieWriteError> {
        let value = cookie.to_signed_header_value(key_ring)?;
        self.try_append_header("Set-Cookie", &value)
            .map_err(ResponseCookieWriteError::from)
    }

    /// Appends one typed cookie encrypted and authenticated with the primary key.
    #[inline]
    pub fn set_private_cookie(
        &mut self,
        cookie: &ResponseCookie,
        key_ring: &CookieKeyRing,
    ) -> Result<&mut Self, ResponseCookieWriteError> {
        let value = cookie.to_private_header_value(key_ring)?;
        self.try_append_header("Set-Cookie", &value)
            .map_err(ResponseCookieWriteError::from)
    }

    /// Appends a cookie removal field with an empty value, `Max-Age=0`, and a
    /// past `Expires` timestamp. The removal scope must match the original
    /// cookie's path/domain.
    #[inline]
    pub fn delete_cookie(
        &mut self,
        removal: &CookieRemoval,
    ) -> Result<&mut Self, ResponseCookieWriteError> {
        let value = removal.to_header_value()?;
        self.try_append_header("Set-Cookie", &value)
            .map_err(ResponseCookieWriteError::from)
    }

    /// Deletes a signed cookie. Removal fields intentionally carry no secret payload.
    #[inline]
    pub fn delete_signed_cookie(
        &mut self,
        removal: &CookieRemoval,
    ) -> Result<&mut Self, ResponseCookieWriteError> {
        self.delete_cookie(removal)
    }

    /// Deletes a private cookie. Removal fields intentionally carry no secret payload.
    #[inline]
    pub fn delete_private_cookie(
        &mut self,
        removal: &CookieRemoval,
    ) -> Result<&mut Self, ResponseCookieWriteError> {
        self.delete_cookie(removal)
    }

    /// Returns the first application-managed value for a valid header name.
    ///
    /// Use [`Self::header_values`] when every value of a repeatable field,
    /// such as `Set-Cookie`, is needed.
    #[inline]
    pub fn header(&self, name: &str) -> Option<&str> {
        let name = parse_header_name(name).ok()?;
        self.headers
            .iter()
            .find(|header| header.name == name)
            .map(|header| {
                std::str::from_utf8(header.value.as_bytes())
                    .expect("response header values originate from UTF-8 strings")
            })
    }

    /// Returns every application-managed value for a valid header name.
    ///
    /// The name is validated with the same policy as header mutation. Values
    /// borrow the response storage, so inspecting repeatable fields does not
    /// clone their contents.
    pub fn header_values<'a>(
        &'a self,
        name: &str,
    ) -> Result<impl Iterator<Item = &'a str> + 'a, ResponseHeaderError> {
        let name = parse_header_name(name)?;
        ensure_application_managed_header(&name)?;
        Ok(self
            .headers
            .iter()
            .filter(move |header| header.name == name)
            .map(|header| {
                std::str::from_utf8(header.value.as_bytes())
                    .expect("response header values originate from UTF-8 strings")
            }))
    }

    /// Checks for an application-managed header using case-insensitive HTTP
    /// name rules.
    ///
    /// Invalid names are reported instead of being confused with an absent
    /// header.
    #[inline]
    pub fn contains_header(&self, name: &str) -> Result<bool, ResponseHeaderError> {
        let name = parse_header_name(name)?;
        ensure_application_managed_header(&name)?;
        Ok(self.headers.iter().any(|header| header.name == name))
    }

    /// Backward-compatible application-header lookup that treats an invalid,
    /// transport-controlled, or hop-by-hop name as absent.
    #[inline]
    pub fn has_header(&self, name: &str) -> bool {
        self.contains_header(name).unwrap_or(false)
    }

    /// Inserts a validated field, replacing every existing value with the
    /// same case-insensitive name.
    ///
    /// Validation and limit checks complete before mutation, so an error
    /// leaves the response unchanged. Transport-controlled and hop-by-hop
    /// fields are rejected rather than silently changed by the transport.
    pub fn try_insert_header(
        &mut self,
        name: &str,
        value: &str,
    ) -> Result<&mut Self, ResponseHeaderError> {
        let (name, value, wire_bytes) =
            validate_header(name, value, self.limits.max_header_bytes())?;
        let mut removed_count = 0usize;
        let mut removed_bytes = 0usize;
        for header in &self.headers {
            if header.name == name {
                removed_count += 1;
                removed_bytes = removed_bytes.checked_add(header.wire_bytes).ok_or(
                    ResponseHeaderError::HeadersTooLarge {
                        limit_bytes: self.limits.max_header_bytes(),
                    },
                )?;
            }
        }

        let next_count = self
            .headers
            .len()
            .checked_sub(removed_count)
            .and_then(|count| count.checked_add(1))
            .ok_or(ResponseHeaderError::TooManyHeaders {
                limit: self.limits.max_header_count(),
            })?;
        ensure_header_count(next_count, self.limits.max_header_count())?;
        let next_bytes = self
            .header_bytes
            .checked_sub(removed_bytes)
            .and_then(|bytes| bytes.checked_add(wire_bytes))
            .ok_or(ResponseHeaderError::HeadersTooLarge {
                limit_bytes: self.limits.max_header_bytes(),
            })?;
        ensure_header_bytes(next_bytes, self.limits.max_header_bytes())?;

        self.headers.retain(|header| header.name != name);
        self.headers.push(StoredHeader {
            name,
            value,
            wire_bytes,
        });
        self.header_bytes = next_bytes;
        Ok(self)
    }

    /// Appends a validated field line.
    ///
    /// Known singleton fields reject duplicates. Extension fields and
    /// standards-defined repeatable fields remain appendable; callers can use
    /// [`Self::try_insert_header`] when authoritative replacement is desired.
    /// Transport-controlled and hop-by-hop fields are rejected.
    pub fn try_append_header(
        &mut self,
        name: &str,
        value: &str,
    ) -> Result<&mut Self, ResponseHeaderError> {
        let (name, value, wire_bytes) =
            validate_header(name, value, self.limits.max_header_bytes())?;
        if self.headers.iter().any(|header| header.name == name)
            && is_singleton_response_header(&name)
        {
            return Err(ResponseHeaderError::DuplicateSingleton);
        }

        let next_count =
            self.headers
                .len()
                .checked_add(1)
                .ok_or(ResponseHeaderError::TooManyHeaders {
                    limit: self.limits.max_header_count(),
                })?;
        ensure_header_count(next_count, self.limits.max_header_count())?;
        let next_bytes = self.header_bytes.checked_add(wire_bytes).ok_or(
            ResponseHeaderError::HeadersTooLarge {
                limit_bytes: self.limits.max_header_bytes(),
            },
        )?;
        ensure_header_bytes(next_bytes, self.limits.max_header_bytes())?;

        self.headers.push(StoredHeader {
            name,
            value,
            wire_bytes,
        });
        self.header_bytes = next_bytes;
        Ok(self)
    }

    /// Removes every application-managed field with the supplied
    /// case-insensitive name.
    pub fn remove_header(&mut self, name: &str) -> Result<usize, ResponseHeaderError> {
        let name = parse_header_name(name)?;
        ensure_application_managed_header(&name)?;
        let previous_count = self.headers.len();
        let mut removed_bytes = 0usize;
        self.headers.retain(|header| {
            if header.name == name {
                removed_bytes += header.wire_bytes;
                false
            } else {
                true
            }
        });
        self.header_bytes -= removed_bytes;
        Ok(previous_count - self.headers.len())
    }

    /// Compatibility alias for append semantics.
    ///
    /// Unlike the former API this method is fallible, so invalid or oversized
    /// data cannot be accepted silently.
    #[deprecated(note = "use try_insert_header or try_append_header to state duplicate intent")]
    pub fn add_header(
        &mut self,
        name: &str,
        value: &str,
    ) -> Result<&mut Self, ResponseHeaderError> {
        self.try_append_header(name, value)
    }

    /// Replaces the body from a static string under the effective budget.
    #[inline]
    pub fn body(&mut self, value: &'static str) -> Result<&mut Self, ResponseBodyError> {
        self.body.full_mut()?.try_replace_slice(value.as_bytes())?;
        Ok(self)
    }

    /// Replaces the body from an owned vector without a transport handoff copy.
    #[inline]
    pub fn body_vec(&mut self, value: Vec<u8>) -> Result<&mut Self, ResponseBodyError> {
        self.set_body_vec(value)
    }

    /// Appends bytes after checking length arithmetic and the effective limit.
    #[inline]
    pub fn write_body(&mut self, value: &[u8]) -> Result<&mut Self, ResponseBodyError> {
        self.body.full_mut()?.try_extend_from_slice(value)?;
        Ok(self)
    }

    /// Returns the first terminal body failure, if application code ignored a
    /// fallible mutation result.
    #[must_use]
    pub fn body_failure(&self) -> Option<ResponseBodyError> {
        self.body.first_failure()
    }

    pub(crate) fn record_body_failure(&mut self, error: ResponseBodyError) {
        if let Ok(body) = self.body.full_mut() {
            if body.first_failure().is_none() {
                body.poison(error);
            }
        }
    }

    /// Returns response metadata without HTTP/1.1 framing.
    ///
    /// All headers have already passed syntax, duplicate, count, and byte
    /// limit checks. The transport never receives an unvalidated field.
    #[doc(hidden)]
    pub fn into_transport_parts(self) -> Result<TransportResponseParts, ResponseBodyError> {
        if let Some(error) = self.body.first_failure() {
            return Err(error);
        }
        debug_assert!(self.headers.len() <= self.limits.max_header_count());
        debug_assert!(self.header_bytes <= self.limits.max_header_bytes());
        debug_assert_eq!(
            self.header_bytes,
            self.headers
                .iter()
                .map(|header| header.wire_bytes)
                .sum::<usize>()
        );
        let status = self.status_code_value();
        let headers = self
            .headers
            .into_iter()
            .map(|header| {
                (
                    header.name.as_str().to_string(),
                    std::str::from_utf8(header.value.as_bytes())
                        .expect("response header values originate from UTF-8 strings")
                        .to_string(),
                )
            })
            .collect();
        let (body, stream) = match self.body {
            ResponseBody::Full(body) => (body.into_bytes()?, None),
            ResponseBody::Stream(body) => (Bytes::new(), Some(body)),
        };

        Ok(TransportResponseParts {
            status,
            headers,
            body,
            stream,
        })
    }
}

fn prepare_headers<'a, I>(
    limits: ResponseLimits,
    headers: I,
) -> Result<(SmallVec<[StoredHeader; INLINE_RESPONSE_HEADERS]>, usize), ResponseWriteError>
where
    I: IntoIterator<Item = (&'a str, &'a str)>,
{
    let mut prepared_headers = SmallVec::<[StoredHeader; INLINE_RESPONSE_HEADERS]>::new();
    let mut prepared_header_bytes = 0usize;
    for (name, value) in headers {
        let (name, value, wire_bytes) = validate_header(name, value, limits.max_header_bytes())?;
        if prepared_headers.iter().any(|header| header.name == name)
            && is_singleton_response_header(&name)
        {
            return Err(ResponseHeaderError::DuplicateSingleton.into());
        }

        let next_count =
            prepared_headers
                .len()
                .checked_add(1)
                .ok_or(ResponseHeaderError::TooManyHeaders {
                    limit: limits.max_header_count(),
                })?;
        ensure_header_count(next_count, limits.max_header_count())?;
        let next_bytes = prepared_header_bytes.checked_add(wire_bytes).ok_or(
            ResponseHeaderError::HeadersTooLarge {
                limit_bytes: limits.max_header_bytes(),
            },
        )?;
        ensure_header_bytes(next_bytes, limits.max_header_bytes())?;

        prepared_headers.push(StoredHeader {
            name,
            value,
            wire_bytes,
        });
        prepared_header_bytes = next_bytes;
    }
    Ok((prepared_headers, prepared_header_bytes))
}

fn parse_header_name(name: &str) -> Result<HeaderName, ResponseHeaderError> {
    // Bound a lookup or mutation name before `http` canonicalizes it.
    header_wire_bytes(name.len(), 0, HARD_MAX_RESPONSE_HEADER_BYTES)?;
    HeaderName::from_bytes(name.as_bytes()).map_err(|_| ResponseHeaderError::InvalidName)
}

fn validate_header(
    name: &str,
    value: &str,
    max_header_bytes: usize,
) -> Result<(HeaderName, HeaderValue, usize), ResponseHeaderError> {
    // Run the allocation-free syntax, ownership, and individual-size checks
    // before `http` canonicalizes the name or copies the value.
    let wire_bytes = validate_response_header_input_with_limit(name, value, max_header_bytes)?;
    let name = parse_header_name(name)?;
    let value =
        HeaderValue::try_from(value.to_owned()).map_err(|_| ResponseHeaderError::InvalidValue)?;
    Ok((name, value, wire_bytes))
}

/// Validates one application response header without retaining or cloning any
/// caller-provided input. `ResponseBuilder` uses this before it owns dynamic
/// names and values, while `Response` repeats the check at its mutation
/// boundary as defense in depth.
pub(crate) fn validate_response_header_input(
    name: &str,
    value: &str,
) -> Result<usize, ResponseHeaderError> {
    validate_response_header_input_with_limit(name, value, HARD_MAX_RESPONSE_HEADER_BYTES)
}

fn validate_response_header_input_with_limit(
    name: &str,
    value: &str,
    max_header_bytes: usize,
) -> Result<usize, ResponseHeaderError> {
    let wire_bytes = header_wire_bytes(name.len(), value.len(), max_header_bytes)?;

    if name.is_empty() || !name.bytes().all(is_header_name_byte) {
        return Err(ResponseHeaderError::InvalidName);
    }
    ensure_application_managed_header_name(name)?;

    // Match `http::HeaderValue`: HTAB, visible ASCII, and obs-text are valid;
    // every other control byte (including CR/LF and DEL) is rejected.
    if !value
        .bytes()
        .all(|byte| byte == b'\t' || (byte >= b' ' && byte != 0x7f))
    {
        return Err(ResponseHeaderError::InvalidValue);
    }

    Ok(wire_bytes)
}

#[inline]
fn is_header_name_byte(byte: u8) -> bool {
    byte.is_ascii_alphanumeric()
        || matches!(
            byte,
            b'!' | b'#'
                | b'$'
                | b'%'
                | b'&'
                | b'\''
                | b'*'
                | b'+'
                | b'-'
                | b'.'
                | b'^'
                | b'_'
                | b'`'
                | b'|'
                | b'~'
        )
}

fn ensure_application_managed_header(name: &HeaderName) -> Result<(), ResponseHeaderError> {
    ensure_application_managed_header_name(name.as_str())
}

fn ensure_application_managed_header_name(name: &str) -> Result<(), ResponseHeaderError> {
    if name.eq_ignore_ascii_case("content-length") || name.eq_ignore_ascii_case("server") {
        return Err(ResponseHeaderError::TransportControlled);
    }
    if [
        "connection",
        "keep-alive",
        "proxy-connection",
        "te",
        "trailer",
        "transfer-encoding",
        "upgrade",
    ]
    .iter()
    .any(|forbidden| name.eq_ignore_ascii_case(forbidden))
    {
        return Err(ResponseHeaderError::HopByHop);
    }
    Ok(())
}

fn header_wire_bytes(
    name_bytes: usize,
    value_bytes: usize,
    max_header_bytes: usize,
) -> Result<usize, ResponseHeaderError> {
    let wire_bytes = name_bytes
        .checked_add(2)
        .and_then(|bytes| bytes.checked_add(value_bytes))
        .and_then(|bytes| bytes.checked_add(2))
        .ok_or(ResponseHeaderError::HeadersTooLarge {
            limit_bytes: max_header_bytes,
        })?;
    ensure_header_bytes(wire_bytes, max_header_bytes)?;
    Ok(wire_bytes)
}

fn ensure_header_count(count: usize, max_headers: usize) -> Result<(), ResponseHeaderError> {
    if count > max_headers {
        return Err(ResponseHeaderError::TooManyHeaders { limit: max_headers });
    }
    Ok(())
}

fn ensure_header_bytes(bytes: usize, max_header_bytes: usize) -> Result<(), ResponseHeaderError> {
    if bytes > max_header_bytes {
        return Err(ResponseHeaderError::HeadersTooLarge {
            limit_bytes: max_header_bytes,
        });
    }
    Ok(())
}

/// Returns whether the field has single-value response semantics. This string
/// form lets `ResponseBuilder` reject a duplicate before owning dynamic input.
pub(crate) fn is_singleton_response_header_name(name: &str) -> bool {
    [
        "content-type",
        "content-location",
        "content-range",
        "location",
        "retry-after",
        "age",
        "date",
        "etag",
        "expires",
        "last-modified",
        "strict-transport-security",
        "x-content-type-options",
        "x-frame-options",
        "access-control-allow-origin",
        "access-control-allow-credentials",
        "access-control-max-age",
    ]
    .iter()
    .any(|singleton| name.eq_ignore_ascii_case(singleton))
}

/// RFC field definitions determine whether duplicate field lines are valid.
/// This bounded list contains response fields whose grammar is a single value
/// and fields where duplicate ambiguity is security-sensitive. Unknown
/// extension fields remain appendable. `Set-Cookie`, `Vary`, `Link`,
/// authentication challenges, and other repeatable fields are intentionally
/// absent.
fn is_singleton_response_header(name: &HeaderName) -> bool {
    is_singleton_response_header_name(name.as_str())
}

#[cfg(test)]
mod tests {
    use super::{
        is_header_name_byte, validate_response_header_input, Response, ResponseBody,
        ResponseBodyError, ResponseCookieWriteError, ResponseHeaderError, ResponseLimits,
        DEFAULT_MAX_RESPONSE_HEADERS as MAX_RESPONSE_HEADERS,
        DEFAULT_MAX_RESPONSE_HEADER_BYTES as MAX_RESPONSE_HEADER_BYTES,
    };
    use crate::{
        BodyBudget, CookieKeyRing, CookieRemoval, CookieSameSite, ResponseCookie,
        ResponseCookieError, MAX_COOKIE_VALUE_BYTES, MIN_COOKIE_KEY_BYTES,
    };
    use std::time::Duration;

    fn expect_header_error(
        result: Result<&mut Response, ResponseHeaderError>,
    ) -> ResponseHeaderError {
        match result {
            Ok(_) => panic!("header mutation unexpectedly succeeded"),
            Err(error) => error,
        }
    }

    #[tokio::test]
    async fn insert_replaces_case_insensitively_and_remove_is_authoritative() {
        let mut response = Response::new().await.unwrap();
        response
            .try_insert_header("Content-Type", "text/plain")
            .unwrap();
        response
            .try_insert_header("content-type", "application/json")
            .unwrap();

        assert_eq!(response.header("CONTENT-TYPE"), Some("application/json"));
        assert!(response.contains_header("CoNtEnT-TyPe").unwrap());
        assert_eq!(response.remove_header("CONTENT-type").unwrap(), 1);
        assert!(!response.contains_header("content-type").unwrap());
    }

    #[test]
    fn allocation_free_header_validation_rejects_empty_and_invalid_names() {
        assert_eq!(
            validate_response_header_input("", "safe"),
            Err(ResponseHeaderError::InvalidName)
        );
        assert_eq!(
            validate_response_header_input("bad:name", "safe"),
            Err(ResponseHeaderError::InvalidName)
        );
        for byte in [b'a', b'Z', b'0', b'!', b'~'] {
            assert!(is_header_name_byte(byte));
        }
        for byte in [0, b' ', b':', b'\r', b'\n', 0x7f, 0x80] {
            assert!(!is_header_name_byte(byte));
        }
    }

    #[tokio::test]
    async fn replacement_at_count_limit_preserves_header_accounting() {
        let mut response = Response::new().await.unwrap();
        for index in 0..MAX_RESPONSE_HEADERS {
            response
                .try_append_header(&format!("x-lily-{index}"), "old")
                .unwrap();
        }
        response
            .try_insert_header("X-Lily-0", "replacement")
            .unwrap();

        let parts = response.into_transport_parts().unwrap();
        assert_eq!(parts.headers.len(), MAX_RESPONSE_HEADERS);
        assert_eq!(
            parts
                .headers
                .iter()
                .find(|(name, _)| name == "x-lily-0")
                .map(|(_, value)| value.as_str()),
            Some("replacement")
        );
    }

    #[tokio::test]
    async fn singleton_append_rejects_duplicate_without_mutation() {
        let mut response = Response::new().await.unwrap();
        response
            .try_append_header("Content-Type", "text/plain")
            .unwrap();

        assert_eq!(
            expect_header_error(response.try_append_header("content-type", "application/json")),
            ResponseHeaderError::DuplicateSingleton
        );
        assert_eq!(response.header("content-type"), Some("text/plain"));
    }

    #[tokio::test]
    async fn set_cookie_and_extension_fields_are_repeatable() {
        let mut response = Response::new().await.unwrap();
        let first = ResponseCookie::new("first", "one")
            .unwrap()
            .http_only(true)
            .secure(true)
            .same_site(CookieSameSite::Lax)
            .path("/")
            .unwrap()
            .max_age(Duration::from_secs(60))
            .unwrap();
        let second = ResponseCookie::new("second", "two").unwrap();
        response.set_cookie(&first).unwrap();
        response.set_cookie(&second).unwrap();
        response.try_append_header("X-Lily-Note", "first").unwrap();
        response.try_append_header("x-lily-note", "second").unwrap();

        let parts = response.into_transport_parts().unwrap();
        assert_eq!(parts.headers.len(), 4);
        assert_eq!(parts.headers[0].0, "set-cookie");
        assert!(parts.headers[0].1.starts_with("first=one"));
        for attribute in ["HttpOnly", "SameSite=Lax", "Secure", "Path=/", "Max-Age=60"] {
            assert!(parts.headers[0].1.contains(attribute));
        }
        assert_eq!(
            parts.headers[1],
            ("set-cookie".to_string(), "second=two".to_string())
        );
        assert_eq!(
            parts.headers[2],
            ("x-lily-note".to_string(), "first".to_string())
        );
        assert_eq!(
            parts.headers[3],
            ("x-lily-note".to_string(), "second".to_string())
        );
    }

    #[tokio::test]
    async fn header_values_borrows_every_repeatable_field_line() {
        let mut response = Response::new().await.unwrap();
        response
            .try_append_header("Vary", "Accept-Encoding")
            .unwrap();
        response.try_append_header("vary", "Origin").unwrap();

        let values: Vec<_> = response.header_values("VARY").unwrap().collect();
        assert_eq!(values, ["Accept-Encoding", "Origin"]);
        let invalid_name = match response.header_values("invalid\r\nname") {
            Ok(_) => panic!("invalid response header lookup unexpectedly succeeded"),
            Err(error) => error,
        };
        assert_eq!(invalid_name, ResponseHeaderError::InvalidName);
        let hop_by_hop = match response.header_values("Connection") {
            Ok(_) => panic!("hop-by-hop response header lookup unexpectedly succeeded"),
            Err(error) => error,
        };
        assert_eq!(hop_by_hop, ResponseHeaderError::HopByHop);
    }

    #[tokio::test]
    async fn crlf_and_invalid_names_fail_closed_without_secret_error_output() {
        let mut response = Response::new().await.unwrap();
        let invalid_name = "X-Secret\r\nInjected";
        let invalid_value = "credential=secret\r\nInjected: yes";

        let name_error = expect_header_error(response.try_append_header(invalid_name, "safe"));
        let value_error =
            expect_header_error(response.try_append_header("X-Secret", invalid_value));

        assert_eq!(name_error, ResponseHeaderError::InvalidName);
        assert_eq!(value_error, ResponseHeaderError::InvalidValue);
        assert_eq!(
            response.contains_header(invalid_name),
            Err(ResponseHeaderError::InvalidName)
        );
        assert_eq!(
            response.remove_header(invalid_name),
            Err(ResponseHeaderError::InvalidName)
        );
        for output in [
            format!("{name_error:?} {name_error}"),
            format!("{value_error:?} {value_error}"),
        ] {
            assert!(!output.contains("X-Secret"));
            assert!(!output.contains("credential=secret"));
            assert!(!output.contains("Injected"));
        }
        assert!(response.into_transport_parts().unwrap().headers.is_empty());
    }

    #[tokio::test]
    #[allow(deprecated)]
    async fn transport_controlled_and_hop_by_hop_headers_fail_before_storage() {
        const FORBIDDEN: [(&str, ResponseHeaderError); 9] = [
            ("Content-Length", ResponseHeaderError::TransportControlled),
            ("Server", ResponseHeaderError::TransportControlled),
            ("Connection", ResponseHeaderError::HopByHop),
            ("Keep-Alive", ResponseHeaderError::HopByHop),
            ("Proxy-Connection", ResponseHeaderError::HopByHop),
            ("TE", ResponseHeaderError::HopByHop),
            ("Trailer", ResponseHeaderError::HopByHop),
            ("Transfer-Encoding", ResponseHeaderError::HopByHop),
            ("Upgrade", ResponseHeaderError::HopByHop),
        ];
        let mut response = Response::new().await.unwrap();
        response
            .try_insert_header("X-Lily-Safe", "retained")
            .unwrap();

        for (name, expected) in FORBIDDEN {
            let secret_value = "credential=lily-secret";
            assert_eq!(
                expect_header_error(response.try_insert_header(name, secret_value)),
                expected
            );
            assert_eq!(
                expect_header_error(response.try_append_header(name, secret_value)),
                expected
            );
            assert_eq!(
                expect_header_error(response.add_header(name, secret_value)),
                expected
            );
            assert_eq!(response.contains_header(name), Err(expected));
            assert_eq!(response.remove_header(name), Err(expected));
            assert_eq!(response.header(name), None);

            let output = format!("{expected:?} {expected}");
            assert!(!output.contains(name));
            assert!(!output.contains("lily-secret"));
        }

        let parts = response.into_transport_parts().unwrap();
        assert_eq!(
            parts.headers,
            vec![("x-lily-safe".to_string(), "retained".to_string())]
        );
    }

    #[tokio::test]
    async fn cookie_mutation_is_typed_bounded_and_atomic() {
        let response = Response::new().await.unwrap();
        assert_eq!(
            ResponseCookie::new("session", "safe\r\ninjected").unwrap_err(),
            ResponseCookieError::InvalidValue
        );

        let oversized = "x".repeat(MAX_COOKIE_VALUE_BYTES + 1);
        assert_eq!(
            ResponseCookie::new("session", &oversized).unwrap_err(),
            ResponseCookieError::ValueTooLong {
                limit_bytes: MAX_COOKIE_VALUE_BYTES
            }
        );
        assert!(response.into_transport_parts().unwrap().headers.is_empty());
    }

    #[tokio::test]
    async fn explicit_cookie_removal_emits_expiry_and_preserves_scope() {
        let mut response = Response::new().await.unwrap();
        let removal = CookieRemoval::new("session")
            .unwrap()
            .path("/")
            .unwrap()
            .domain("example.com")
            .unwrap();

        response.delete_cookie(&removal).unwrap();

        let value = response.header("set-cookie").unwrap();
        assert!(value.starts_with("session="));
        assert!(value.contains("Path=/"));
        assert!(value.contains("Domain=example.com"));
        assert!(value.contains("Max-Age=0"));
        assert!(value.contains("Expires="));
    }

    #[tokio::test]
    async fn secure_cookie_writes_and_removals_use_repeatable_atomic_headers() {
        let ring = CookieKeyRing::new(&[0x42; MIN_COOKIE_KEY_BYTES]).unwrap();
        let cookie = ResponseCookie::new("session", "secret")
            .unwrap()
            .secure(true)
            .http_only(true);
        let removal = CookieRemoval::new("session")
            .unwrap()
            .path("/")
            .unwrap()
            .partitioned(true);
        let mut response = Response::new().await.unwrap();

        response.set_signed_cookie(&cookie, &ring).unwrap();
        response.set_private_cookie(&cookie, &ring).unwrap();
        response.delete_signed_cookie(&removal).unwrap();
        response.delete_private_cookie(&removal).unwrap();

        let values = response
            .header_values("set-cookie")
            .unwrap()
            .collect::<Vec<_>>();
        assert_eq!(values.len(), 4);
        assert!(values[0].contains("secret"));
        assert!(!values[1].contains("secret"));
        for removal in &values[2..] {
            assert!(removal.contains("Max-Age=0"));
            assert!(removal.contains("Expires="));
            assert!(removal.contains("Partitioned"));
            assert!(removal.contains("Secure"));
        }
    }

    #[tokio::test]
    async fn secure_cookie_encoding_failure_does_not_mutate_response() {
        let ring = CookieKeyRing::new(&[0x42; MIN_COOKIE_KEY_BYTES]).unwrap();
        let oversized =
            ResponseCookie::new("session", &"x".repeat(MAX_COOKIE_VALUE_BYTES)).unwrap();
        let mut response = Response::new().await.unwrap();

        let error = match response.set_private_cookie(&oversized, &ring) {
            Ok(_) => panic!("private cookie mutation unexpectedly succeeded"),
            Err(error) => error,
        };
        assert_eq!(
            error,
            ResponseCookieWriteError::Cookie(ResponseCookieError::SerializedTooLarge {
                limit_bytes: crate::MAX_SET_COOKIE_BYTES
            })
        );
        assert!(response
            .header_values("set-cookie")
            .unwrap()
            .next()
            .is_none());
    }

    #[tokio::test]
    async fn cookie_write_respects_response_header_limit_without_mutation() {
        let limits = ResponseLimits::new(BodyBudget::default(), 4, 24).unwrap();
        let mut response = Response::with_limits(limits).await.unwrap();
        let cookie = ResponseCookie::new("session", "opaque-value").unwrap();

        let error = match response.set_cookie(&cookie) {
            Ok(_) => panic!("cookie mutation unexpectedly succeeded"),
            Err(error) => error,
        };
        assert_eq!(
            error,
            ResponseCookieWriteError::Header(ResponseHeaderError::HeadersTooLarge {
                limit_bytes: 24
            })
        );
        assert!(response.into_transport_parts().unwrap().headers.is_empty());
    }

    #[tokio::test]
    async fn header_count_limit_is_atomic() {
        let mut response = Response::new().await.unwrap();
        for index in 0..MAX_RESPONSE_HEADERS {
            response
                .try_append_header(&format!("x-lily-{index}"), "value")
                .unwrap();
        }

        assert_eq!(
            expect_header_error(response.try_append_header("x-one-too-many", "value")),
            ResponseHeaderError::TooManyHeaders {
                limit: MAX_RESPONSE_HEADERS
            }
        );
        assert_eq!(
            response.into_transport_parts().unwrap().headers.len(),
            MAX_RESPONSE_HEADERS
        );
    }

    #[tokio::test]
    async fn aggregate_header_byte_limit_is_atomic() {
        let mut response = Response::new().await.unwrap();
        let name = "x-aggregate";
        let value = "x".repeat(MAX_RESPONSE_HEADER_BYTES - name.len() - 4);
        response.try_append_header(name, &value).unwrap();

        assert_eq!(
            expect_header_error(response.try_append_header("x-extra", "x")),
            ResponseHeaderError::HeadersTooLarge {
                limit_bytes: MAX_RESPONSE_HEADER_BYTES
            }
        );
        let parts = response.into_transport_parts().unwrap();
        assert_eq!(parts.headers.len(), 1);
        assert_eq!(parts.headers[0].1.len(), value.len());
    }

    #[tokio::test]
    async fn oversized_replacement_preserves_the_previous_value() {
        let mut response = Response::new().await.unwrap();
        response
            .try_insert_header("Content-Type", "text/plain")
            .unwrap();
        let oversized = "x".repeat(MAX_RESPONSE_HEADER_BYTES);

        assert!(matches!(
            response.try_insert_header("content-type", &oversized),
            Err(ResponseHeaderError::HeadersTooLarge { .. })
        ));
        assert_eq!(response.header("content-type"), Some("text/plain"));
    }

    #[tokio::test]
    #[allow(deprecated)]
    async fn legacy_add_header_is_fallible_and_fail_closed() {
        let mut response = Response::new().await.unwrap();

        assert_eq!(
            expect_header_error(response.add_header("X-Test", "secret\r\nInjected: yes")),
            ResponseHeaderError::InvalidValue
        );
        assert!(response.into_transport_parts().unwrap().headers.is_empty());
    }

    #[tokio::test]
    async fn body_limit_failure_is_terminal_and_never_emits_a_partial_success() {
        let limits = ResponseLimits::new(BodyBudget::new(4).unwrap(), 4, 128).unwrap();
        let mut response = Response::with_limits(limits).await.unwrap();
        response.status(201, "Created");
        response.write_body(b"ab").unwrap();
        let capacity_before = match &response.body {
            ResponseBody::Full(body) => body.data.capacity(),
            ResponseBody::Stream(_) => panic!("expected buffered body"),
        };

        let error = match response.write_body(b"cde") {
            Ok(_) => panic!("oversized body append unexpectedly succeeded"),
            Err(error) => error,
        };
        assert_eq!(error, ResponseBodyError::LimitExceeded { limit_bytes: 4 });
        match &response.body {
            ResponseBody::Full(body) => {
                assert_eq!(body.data.capacity(), capacity_before);
                assert!(body.data.is_empty());
            }
            ResponseBody::Stream(_) => panic!("expected buffered body"),
        }
        assert_eq!(response.body_failure(), Some(error));
        assert_eq!(response.into_transport_parts().unwrap_err(), error);
    }

    #[tokio::test]
    async fn exact_body_limit_succeeds_and_owned_transport_handoff_is_zero_copy() {
        let limits = ResponseLimits::new(BodyBudget::new(4).unwrap(), 4, 128).unwrap();
        let mut response = Response::with_limits(limits).await.unwrap();
        let body = Vec::from(*b"lily");
        let allocation = body.as_ptr();

        response.body_vec(body).unwrap();
        let parts = response.into_transport_parts().unwrap();

        assert_eq!(parts.body.as_ref(), b"lily");
        assert_eq!(parts.body.as_ptr(), allocation);
    }

    #[tokio::test]
    async fn effective_response_header_limits_replace_static_defaults() {
        let expanded = ResponseLimits::new(
            BodyBudget::default(),
            MAX_RESPONSE_HEADERS + 1,
            MAX_RESPONSE_HEADER_BYTES,
        )
        .unwrap();
        let mut response = Response::with_limits(expanded).await.unwrap();
        for index in 0..=MAX_RESPONSE_HEADERS {
            response
                .try_append_header(&format!("x-expanded-{index}"), "v")
                .unwrap();
        }
        assert_eq!(
            response.into_transport_parts().unwrap().headers.len(),
            MAX_RESPONSE_HEADERS + 1
        );

        let constrained =
            ResponseLimits::new(BodyBudget::default(), 1, MAX_RESPONSE_HEADER_BYTES).unwrap();
        let mut response = Response::with_limits(constrained).await.unwrap();
        response.try_append_header("x-first", "v").unwrap();
        assert_eq!(
            expect_header_error(response.try_append_header("x-second", "v")),
            ResponseHeaderError::TooManyHeaders { limit: 1 }
        );
    }
}
