[package]
name = "lily_injectable_derive"
version = "0.1.0"
edition = "2024"
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true
exclude = ["examples/**", "tests/**"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
proc-macro-crate = "3"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
[dev-dependencies]
lily_error = { version = "0.1.0", path = "../lily_error" }
lily_injection_registry = { version = "0.1.0", path = "../lily_injection_registry" }
lily_injection = { path = "../lily_injection" }
tokio = { version = "1.0", features = ["full"] }
linkme = { workspace = true }
trybuild = "1.0"
