// =============================================================================
// 1. ASYNC HANDLER IMPLEMENTATION WITH HRTB
// =============================================================================

use lily_error::application::http_api::HttpApiError;
use lily_injection::Extensions;
use lily_web_core::{
    write_error_response, Request, Response, ResponseWriteError, ResponseWriteOutcome,
};
use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

/// Boxed request future returned by Lily's hidden action-adapter contract.
#[doc(hidden)]
pub type HttpActionFuture<'a> =
    Pin<Box<dyn Future<Output = Result<ResponseWriteOutcome, ResponseWriteError>> + Send + 'a>>;

type LegacyHttpActionFuture<'a> =
    Pin<Box<dyn Future<Output = Result<(), HttpApiError>> + Send + 'a>>;

/// Object-safe request adapter used by a materialized route.
///
/// Struct-controller expansions implement this trait for an action-specific
/// adapter that owns one build-time `Arc<Controller>`. Calling the adapter
/// borrows that reference; no controller lookup, downcast, or `Arc` clone is
/// performed on the request path.
#[doc(hidden)]
pub trait HttpAction: Send + Sync + 'static {
    fn call<'a>(
        &'a self,
        extensions: Arc<Extensions>,
        request: &'a mut Request,
        response: &'a mut Response,
    ) -> HttpActionFuture<'a>;
}

type ClosureHttpActionFn = dyn for<'a> Fn(Arc<Extensions>, &'a mut Request, &'a mut Response) -> LegacyHttpActionFuture<'a>
    + Send
    + Sync
    + 'static;

struct ClosureHttpAction {
    handler: Arc<ClosureHttpActionFn>,
}

impl HttpAction for ClosureHttpAction {
    fn call<'a>(
        &'a self,
        extensions: Arc<Extensions>,
        request: &'a mut Request,
        response: &'a mut Response,
    ) -> HttpActionFuture<'a> {
        Box::pin(async move {
            match (self.handler)(extensions, request, response).await {
                Ok(()) => Ok(ResponseWriteOutcome::Preserved),
                Err(error) => write_error_response(error, response, request).await,
            }
        })
    }
}

/// Hidden type-erased action retained by the immutable route table.
#[doc(hidden)]
#[derive(Clone)]
pub struct Handler {
    action: Arc<dyn HttpAction>,
}

impl Handler {
    /// Create a new async handler with HRTB
    #[allow(clippy::type_complexity)]
    ///
    pub fn new(
        handler: Arc<
            dyn for<'a> Fn(
                    Arc<Extensions>,
                    &'a mut Request,
                    &'a mut Response,
                )
                    -> Pin<Box<dyn Future<Output = Result<(), HttpApiError>> + Send + 'a>>
                + Send
                + Sync
                + 'static,
        >,
        _legacy_supports_tls: bool,
    ) -> Self {
        Self {
            action: Arc::new(ClosureHttpAction { handler }),
        }
    }

    /// Bind an action-specific adapter to a route.
    ///
    /// Public only for code generated by `lily_http_api_macros`.
    #[doc(hidden)]
    pub fn from_action<A>(action: A, _legacy_supports_tls: bool) -> Self
    where
        A: HttpAction,
    {
        Self {
            action: Arc::new(action),
        }
    }

    /// Call the async handler
    pub(crate) async fn call(
        &self,
        extensions: Arc<Extensions>,
        req: &mut Request,
        rsp: &mut Response,
    ) -> Result<ResponseWriteOutcome, ResponseWriteError> {
        self.action.call(extensions, req, rsp).await
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use lily_injection::ApplicationContainer;
    use std::sync::atomic::{AtomicBool, AtomicUsize, Ordering};

    struct ControllerProbe {
        calls: AtomicUsize,
    }

    struct BorrowingAction {
        controller: Arc<ControllerProbe>,
        observed_clone: Arc<AtomicBool>,
    }

    impl HttpAction for BorrowingAction {
        fn call<'a>(
            &'a self,
            _extensions: Arc<Extensions>,
            _request: &'a mut Request,
            _response: &'a mut Response,
        ) -> HttpActionFuture<'a> {
            Box::pin(async move {
                if Arc::strong_count(&self.controller) != 1 {
                    self.observed_clone.store(true, Ordering::SeqCst);
                }
                self.controller.calls.fetch_add(1, Ordering::SeqCst);
                tokio::task::yield_now().await;
                if Arc::strong_count(&self.controller) != 1 {
                    self.observed_clone.store(true, Ordering::SeqCst);
                }
                Ok(ResponseWriteOutcome::Preserved)
            })
        }
    }

    #[tokio::test]
    async fn action_adapter_borrows_one_controller_reference_across_concurrent_calls() {
        let container = ApplicationContainer::build()
            .await
            .expect("handler fixture container builds");
        let controller = Arc::new(ControllerProbe {
            calls: AtomicUsize::new(0),
        });
        let controller_weak = Arc::downgrade(&controller);
        let observed_clone = Arc::new(AtomicBool::new(false));
        let handler = Handler::from_action(
            BorrowingAction {
                controller,
                observed_clone: Arc::clone(&observed_clone),
            },
            false,
        );

        let mut tasks = Vec::new();
        for _ in 0..16 {
            let handler = handler.clone();
            let extensions = container.services();
            tasks.push(tokio::spawn(async move {
                let mut request = Request::from_transport_parts(
                    "GET".to_string(),
                    "/controller".to_string(),
                    Vec::new(),
                    &[],
                )
                .await
                .expect("request builds");
                let mut response = Response::new().await.expect("response builds");
                handler
                    .call(extensions, &mut request, &mut response)
                    .await
                    .expect("action succeeds");
            }));
        }
        for task in tasks {
            task.await.expect("request task joins");
        }

        let controller = controller_weak
            .upgrade()
            .expect("handler retains the controller");
        assert_eq!(controller.calls.load(Ordering::SeqCst), 16);
        assert!(!observed_clone.load(Ordering::SeqCst));
        drop(controller);
        drop(handler);
        assert!(controller_weak.upgrade().is_none());
        container
            .close()
            .await
            .expect("handler fixture container closes");
    }
}
