#![deny(missing_docs)]
#![deny(rustdoc::broken_intra_doc_links)]

//! Procedural derives for Lily's typed ClickHouse adapters.
//!
//! Applications normally import these derives from `lily_clickhouse`; a direct
//! dependency on this proc-macro crate is unnecessary.
//!
//! [`ClickhouseSchema`] is the entity metadata layer. [`ClickhouseTable`]
//! generates a typed table API and its DI lifecycle. [`ClickhouseRepository`]
//! is an optional convenience delegating to that table; a domain service may
//! inject the generated table directly instead.
//!
//! # Single mode
//!
//! ```ignore
//! #[derive(Injectable, ClickhouseTable, Default)]
//! #[entity_type(AuditEvent)]
//! #[service(lifetime = "Singleton")]
//! struct AuditTable {
//!     #[inject]
//!     db: Arc<DatabaseService>,
//! }
//! ```
//!
//! # Factory mode
//!
//! Factory tables additionally declare `#[cell_name("analytics")]`, inject a
//! field named `clickhouse_factory: Arc<ClickhouseFactory>`, and retain an
//! unannotated `db: Arc<DatabaseService>` field. The generated initializer
//! selects the named cell and assigns `db`.
//!
//! Both table and repository derives implement `lily_injection::ServiceTrait`.
//! Do not supply a competing manual implementation.

use proc_macro::TokenStream;

mod repository;
mod schema;
mod table;
mod type_mapper;
mod utils;

/// Generates a lifecycle-aware typed ClickHouse table adapter.
///
/// `#[entity_type(Entity)]` is required, and `Entity` must implement the
/// metadata contract generated by [`ClickhouseSchema`]. `#[cell_name("...")]`
/// is optional and selects factory mode. The table name, columns and ordering
/// come from the entity schema; this derive has no `table` or `order_by`
/// attributes of its own.
///
/// Generated inherent methods are intentional application API: table/schema
/// metadata, migration DDL, bounded contexts and typed insert/select/count/
/// delete operations. A domain service may inject this table without defining
/// a repository. The derive also implements `ServiceTrait`.
#[proc_macro_derive(ClickhouseTable, attributes(entity_type, cell_name))]
pub fn derive_clickhouse_table(input: TokenStream) -> TokenStream {
    table::derive_impl(input)
}

/// Generates an optional repository convenience over a typed table.
///
/// `#[table_type(Table)]` and `#[entity_type(Entity)]` are required. The input
/// must contain a field named `table`, canonically
/// `#[inject] table: Arc<Table>`. Generated methods delegate to the table and
/// the derive implements `ServiceTrait`; it is not a mandatory persistence
/// layer.
#[proc_macro_derive(ClickhouseRepository, attributes(table_type, entity_type))]
pub fn derive_clickhouse_repository(input: TokenStream) -> TokenStream {
    repository::derive_impl(input)
}

/// Generates validated ClickHouse schema metadata for a row type.
///
/// Automatically generates ClickHouse schema from Rust struct definitions.
/// Implements the `ClickhouseSchemaProvider` trait with compile-time type mapping.
///
/// # Container Attributes
///
/// - `#[clickhouse(table = "...")]` - Override table name (default: lowercase struct name)
/// - `#[clickhouse(order_by = "...")]` - Required non-empty list of declared columns
/// - `#[clickhouse(engine = "MergeTree()")]` - Optional; V1 accepts only `MergeTree()`
///
/// # Field Attributes
///
/// - `#[clickhouse(type = "...")]` - Override the validated ClickHouse type expression
///
/// # Automatic Type Mapping
///
/// - `String`, `&str` → `String`
/// - `u8`, `u16`, `u32`, `u64`, `u128` → `UInt8`, `UInt16`, `UInt32`, `UInt64`, `UInt128`
/// - `i8`, `i16`, `i32`, `i64`, `i128` → `Int8`, `Int16`, `Int32`, `Int64`, `Int128`
/// - `f32`, `f64` → `Float32`, `Float64`
/// - `bool` → `Boolean`
/// - `Option<T>` → `Nullable(T)`
/// - `Vec<T>` → `Array(T)`
///
/// # Example
///
/// ```rust,ignore
/// #[derive(Debug, Clone, Serialize, Deserialize, clickhouse::Row, ClickhouseSchema)]
/// #[clickhouse(table = "users", order_by = "id, created_at", engine = "MergeTree()")]
/// pub struct User {
///     pub id: String,
///     pub email: String,
///     pub age: u32,
///     #[clickhouse(type = "UInt64")]
///     pub created_at: u64,
///     pub is_active: bool,
/// }
///
/// // Auto-generated:
/// // impl ClickhouseSchemaProvider for User {
/// //     fn schema() -> &'static str { "id String, email String, age UInt32, created_at UInt64, is_active Boolean" }
/// //     fn table_name() -> &'static str { "users" }
/// //     fn order_by() -> &'static str { "id, created_at" }
/// //     fn engine() -> &'static str { "MergeTree()" }
/// // }
/// ```
#[proc_macro_derive(ClickhouseSchema, attributes(clickhouse))]
pub fn derive_clickhouse_schema(input: TokenStream) -> TokenStream {
    schema::derive_impl(input)
}
