[package]
name = "lily_mongodb_derive"
version = "0.1.0"
edition = "2024"
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[features]
default = ["single"]
single = []
factory = []

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
proc-macro-crate = "3"

[dev-dependencies]
lily_mongodb = { path = "../lily_mongodb", default-features = false }
lily_injection = { path = "../../foundation/lily_injection" }
async-trait = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
trybuild = "1.0"
