use crate::storage::FrameworkSingletonAttachment;
use crate::{Extensions, ProcessContext};
use lily_injection_registry::ServiceDisposeFn;
use std::sync::Arc;

/// Attach one dependency-free framework-owned handle while an application
/// adapter is building its immutable runtime graph.
#[doc(hidden)]
pub fn attach_framework_singleton<T>(
    extensions: &Arc<Extensions>,
    service: Arc<T>,
) -> Result<FrameworkSingletonAttachment<T>, lily_error::injection::InjectionError>
where
    T: Send + Sync + 'static,
{
    extensions.attach_framework_singleton(service)
}

/// Cancellation guard used only by code generated by
/// `lily_injectable_derive`.
///
/// A service is mutable while `initialize(&mut self)` runs, so it cannot enter
/// an `Arc` lifecycle ledger beforehand. If the factory future is cancelled,
/// this guard moves the partial value into the owning request/root ledger from
/// `Drop`. Cleanup can then invoke its async disposer through the container-
/// owned shutdown path instead of silently dropping a live resource.
#[doc(hidden)]
pub struct InitializationGuard<T>
where
    T: Send + Sync + 'static,
{
    service: Option<T>,
    extensions: Arc<Extensions>,
    context: Option<ProcessContext>,
    type_name: &'static str,
    dispose_fn: ServiceDisposeFn,
}

impl<T> InitializationGuard<T>
where
    T: Send + Sync + 'static,
{
    #[doc(hidden)]
    pub fn new(
        service: T,
        extensions: Arc<Extensions>,
        type_name: &'static str,
        dispose_fn: ServiceDisposeFn,
    ) -> Self {
        Self {
            service: Some(service),
            extensions,
            context: ProcessContext::current(),
            type_name,
            dispose_fn,
        }
    }

    #[doc(hidden)]
    pub fn service_mut(&mut self) -> &mut T {
        self.service
            .as_mut()
            .expect("initialization guard was already disarmed")
    }

    #[doc(hidden)]
    pub fn service(&self) -> &T {
        self.service
            .as_ref()
            .expect("initialization guard was already disarmed")
    }

    #[doc(hidden)]
    pub fn into_service(mut self) -> T {
        self.service
            .take()
            .expect("initialization guard was already disarmed")
    }
}

impl<T> Drop for InitializationGuard<T>
where
    T: Send + Sync + 'static,
{
    fn drop(&mut self) {
        let Some(service) = self.service.take() else {
            return;
        };
        let value: Arc<dyn std::any::Any + Send + Sync> = Arc::new(service);
        self.extensions.track_cancelled_initialization(
            self.context.as_ref(),
            self.type_name,
            value,
            self.dispose_fn,
        );
    }
}
