#![deny(missing_docs)]
#![deny(rustdoc::broken_intra_doc_links)]

//! DTO-facing CRUD contract used by Lily's generated service layer.
//!
//! # When to use this crate
//!
//! Use [`BaseService`] when a controller, gateway or consumer needs the small,
//! conventional CRUD surface generated by `#[derive(CrudService)]`. It is not
//! a superclass that every Lily service must implement. Domain services with
//! commands, searches or provider-specific behavior should expose their own
//! application trait instead.
//!
//! `Dto` is the caller-facing type. `Entity` is the persistence type used to
//! select the matching generated implementation; it deliberately never
//! crosses this trait's method boundary. The built-in `CrudService` derive is
//! currently backed by `lily_mongo_repository::MongoRepository` and therefore
//! treats string IDs as MongoDB ObjectId text.
//!
//! # Calling a service
//!
//! Call methods through the trait. Importing [`BaseService`] is required for
//! method syntax when the concrete type receives its implementation from the
//! derive macro.
//!
//! ```
//! use lily_mongo_service::{BaseService, BaseServiceError};
//!
//! struct UserDto;
//! struct UserEntity;
//!
//! async fn load_user<S>(service: &S, id: &str) -> Result<UserDto, BaseServiceError>
//! where
//!     S: BaseService<UserDto, UserEntity>,
//! {
//!     service.find_by_id(id).await
//! }
//! ```
//!
//! # Normal application composition
//!
//! `CrudService` and `Injectable` have different responsibilities:
//!
//! - `CrudService` implements [`BaseService`] by calling
//!   `MongoRepository<Entity>` and converting between `Dto` and `Entity`.
//! - `Injectable` publishes link-time registration metadata, records every
//!   `#[inject] Arc<T>` field as a dependency and constructs the service from
//!   the application-owned `Extensions` provider.
//! - `ServiceTrait` supplies the lifecycle contract required by `Injectable`.
//!   `CrudService` does not implement it, so a normal no-op service declares
//!   `impl ServiceTrait for DomainService {}` explicitly.
//!
//! Application code does not manually add this service to
//! `lily_injection_registry`. Building the application container discovers the
//! metadata generated by `Injectable`, validates the graph and eagerly creates
//! singleton services in dependency-first order.
//!
//! ```ignore
//! use std::sync::Arc;
//!
//! use lily_injection::{Injectable, ServiceTrait};
//! use lily_mongodb::CrudService;
//!
//! #[derive(Injectable, CrudService, Default)]
//! #[dto_type(DomainDto)]
//! #[entity_type(Domain)]
//! #[repository_type(DomainRepository)]
//! #[service(lifetime = "Singleton")]
//! pub struct DomainService {
//!     #[inject]
//!     repository: Arc<DomainRepository>,
//! }
//!
//! impl ServiceTrait for DomainService {}
//!
//! // Required by CrudService:
//! // impl From<DomainDto> for Domain { ... }
//! // impl From<Domain> for DomainDto { ... }
//! // DomainRepository: MongoRepository<Domain>
//! ```
//!
//! The repository must itself be registered—normally with
//! `#[derive(Injectable, Repository, Default)]`, an injected generated
//! collection, the same lifetime, and its own `ServiceTrait` implementation.
//! The collection is normally `#[derive(Injectable, MongoCollection, Default)]`;
//! `MongoCollection` supplies the collection's lifecycle implementation.
//!
//! # Optional gateway notifications
//!
//! `#[gateway(DomainGateway)]` enables best-effort notifications after
//! successful generated writes. The service must then contain an
//! `#[inject] gateway: Arc<DomainGateway>` field. That gateway must expose the
//! notification methods generated by Lily's gateway derive. Notification
//! failure is logged and does not roll back an already successful database
//! operation.
//!
//! ```ignore
//! #[derive(Injectable, CrudService, Default)]
//! #[gateway(DomainGateway)]
//! #[dto_type(DomainDto)]
//! #[entity_type(Domain)]
//! #[repository_type(DomainRepository)]
//! #[service(lifetime = "Singleton")]
//! pub struct DomainService {
//!     #[inject]
//!     gateway: Arc<DomainGateway>,
//!     #[inject]
//!     repository: Arc<DomainRepository>,
//! }
//!
//! impl ServiceTrait for DomainService {}
//! ```
//!
//! `Default` is needed when the service owns non-injected runtime state;
//! dependency-only named structs can be constructed directly by `Injectable`.
//! It may be omitted in that case—deriving it unnecessarily also requires
//! every field type to implement `Default`. Omitting
//! `#[service(lifetime = "...")]` selects `Transient`, so singleton data-layer
//! components should state their lifetime explicitly.
//!
//! Applications normally import `BaseService`, its error types and `CrudService`
//! from `lily_mongodb`. The derive lives in `lily_mongodb_derive`; its generated
//! calls, including optional gateway tracing, use that facade. Extra direct
//! dependencies on this contract crate, `lily_mongo_repository`, trace, registry
//! or macro helper packages are unnecessary. DI registration uses `lily_injection`
//! or an HTTP/WebSocket/Consumer facade; gateway types remain application-owned.
//!
//! # Domain-specific repository calls
//!
//! Additional service methods remain ordinary inherent methods. They use the
//! injected repository and the current `lily_mongo_repository::MongoRepository`
//! contract: construct a `MongoFilter`, choose a `MongoOperationContext`, call
//! `find_one`, and convert the returned entity to the DTO. There is no
//! framework `find_one_dto(Document)` method in the current public API.
//!
//! ```ignore
//! use lily_mongodb::{
//!     MongoFilter, MongoOperationContext, MongoRepository, MongoRepositoryError,
//! };
//! use mongodb::bson::doc;
//!
//! impl DomainService {
//!     pub async fn find_by_application_id(
//!         &self,
//!         id: &str,
//!     ) -> Result<Option<DomainDto>, MongoRepositoryError> {
//!         let filter = MongoFilter::new(doc! { "application_id": id })?;
//!         let operation = MongoOperationContext::detached();
//!         let entity = MongoRepository::<Domain>::find_one(
//!             self.repository.as_ref(),
//!             filter,
//!             &operation,
//!         )
//!         .await?;
//!
//!         Ok(entity.map(DomainDto::from))
//!     }
//! }
//! ```
//!
//! A domain that requires a record to exist should convert `None` into its own
//! domain or transport error instead of silently inventing a DTO.
//!
//! Generated calls create an independent Mongo operation context per method.
//! Applications that require a shared transaction, deadline, cancellation
//! token or domain-specific not-found policy should implement a dedicated
//! service method instead of trying to configure the generated call implicitly.

use async_trait::async_trait;

/// Error and operation vocabulary emitted by [`BaseService`].
pub use lily_error::application::base_service::{BaseServiceError, BaseServiceOperation};

/// Conventional DTO/entity CRUD service contract.
///
/// `Dto` is the caller-facing model and `Entity` is the persistence model.
/// Implementations are responsible for converting between them. The entity
/// type remains part of the trait identity even though it is never exposed as
/// a method parameter or result.
///
/// The generated implementation is normally placed on an
/// `#[derive(Injectable, CrudService)]` service with an injected
/// `Arc<Repository>`. This trait intentionally contains no list/search/filter
/// API and no transaction parameter. Add domain-specific methods on the
/// concrete service or a separate application trait rather than widening
/// filters into the DTO boundary.
#[async_trait]
pub trait BaseService<Dto, Entity>: Send + Sync
where
    Dto: Send + Sync + 'static,
    Entity: Send + Sync + 'static,
{
    /// Persists one DTO and returns its canonical persisted representation.
    ///
    /// Generated MongoDB services populate the persisted `_id` before
    /// converting the entity back into `Dto`.
    async fn create(&self, dto: Dto) -> Result<Dto, BaseServiceError>;

    /// Persists a bounded batch and returns canonical persisted DTOs in input
    /// order.
    ///
    /// The trait does not promise transaction-level atomicity. The generated
    /// MongoDB adapter rejects empty or oversized batches before I/O.
    async fn create_many(&self, dtos: Vec<Dto>) -> Result<Vec<Dto>, BaseServiceError>;

    /// Replaces the persisted entity identified by the DTO and returns the
    /// resulting canonical DTO.
    ///
    /// The generated MongoDB adapter requires a non-null `_id` in the converted
    /// entity. This method is not a partial patch operation.
    async fn update(&self, dto: Dto) -> Result<Dto, BaseServiceError>;

    /// Deletes the entity identified by the DTO.
    ///
    /// Only the converted entity's identifier selects the target in the
    /// generated adapter. Returns `false` when no entity exists.
    async fn delete(&self, dto: Dto) -> Result<bool, BaseServiceError>;

    /// Deletes the entities identified by the supplied DTOs and returns the
    /// number removed.
    ///
    /// The generated adapter extracts only identifiers, rejects an empty or
    /// oversized batch and does not treat a zero count as an error.
    async fn delete_many(&self, dtos: Vec<Dto>) -> Result<u64, BaseServiceError>;

    /// Finds one DTO by its external string identifier.
    ///
    /// Absence is returned as [`BaseServiceError::NotFound`], not as `Option`.
    /// The generated MongoDB adapter requires 24-character hexadecimal
    /// ObjectId text.
    async fn find_by_id(&self, id: &str) -> Result<Dto, BaseServiceError>;

    /// Deletes one entity by external string identifier.
    ///
    /// Returns `false` when the identifier is valid but no entity exists. An
    /// invalid identifier is an operation failure.
    async fn delete_by_id(&self, id: &str) -> Result<bool, BaseServiceError>;

    /// Finds the entities whose IDs appear in a bounded identifier batch.
    ///
    /// Missing IDs are omitted; absence is not an error. Callers must not rely
    /// on the output preserving the input ID order unless their concrete
    /// implementation documents that stronger guarantee. The generated
    /// MongoDB adapter rejects an empty batch.
    async fn find_by_ids(&self, ids: Vec<String>) -> Result<Vec<Dto>, BaseServiceError>;
}

#[cfg(test)]
mod tests {
    use super::{BaseService, BaseServiceError};
    use async_trait::async_trait;
    use std::marker::PhantomData;

    struct Contract<Dto, Entity>(PhantomData<(Dto, Entity)>);

    #[async_trait]
    impl<Dto, Entity> BaseService<Dto, Entity> for Contract<Dto, Entity>
    where
        Dto: Send + Sync + 'static,
        Entity: Send + Sync + 'static,
    {
        async fn create(&self, dto: Dto) -> Result<Dto, BaseServiceError> {
            Ok(dto)
        }

        async fn create_many(&self, dtos: Vec<Dto>) -> Result<Vec<Dto>, BaseServiceError> {
            Ok(dtos)
        }

        async fn update(&self, dto: Dto) -> Result<Dto, BaseServiceError> {
            Ok(dto)
        }

        async fn delete(&self, _dto: Dto) -> Result<bool, BaseServiceError> {
            Ok(true)
        }

        async fn delete_many(&self, dtos: Vec<Dto>) -> Result<u64, BaseServiceError> {
            Ok(dtos.len() as u64)
        }

        async fn find_by_id(&self, id: &str) -> Result<Dto, BaseServiceError> {
            Err(BaseServiceError::not_found("Entity", id))
        }

        async fn delete_by_id(&self, _id: &str) -> Result<bool, BaseServiceError> {
            Ok(false)
        }

        async fn find_by_ids(&self, _ids: Vec<String>) -> Result<Vec<Dto>, BaseServiceError> {
            Ok(Vec::new())
        }
    }

    #[tokio::test]
    async fn contract_does_not_require_a_storage_provider() {
        let service = Contract::<String, u64>(PhantomData);
        assert_eq!(service.create("dto".to_string()).await.unwrap(), "dto");
        assert!(matches!(
            service.find_by_id("missing").await,
            Err(BaseServiceError::NotFound { entity, identifier })
                if entity == "Entity" && identifier == "missing"
        ));
    }
}
