[package]
name = "mongodb-derive-contract"
version = "0.0.0"
edition = "2024"
publish = false

[features]
default = ["single"]
single = ["lily_mongodb/single"]
factory = [
    "dep:lily_injectable_derive",
    "dep:lily_injection_registry",
    "dep:linkme",
    "lily_mongodb/factory",
]
wrong-service = []
manual-collision = []

[dependencies]
async-trait = "0.1"
futures = "0.3"
lily_mongo_repository = { path = "../../../crates/integrations/lily_mongo_repository" }
lily_error = { path = "../../../crates/foundation/lily_error" }
lily_injectable_derive = { path = "../../../crates/foundation/lily_injectable_derive", optional = true }
lily_injection = { path = "../../../crates/foundation/lily_injection" }
lily_injection_registry = { path = "../../../crates/foundation/lily_injection_registry", optional = true }
lily_mongodb = { path = "../../../crates/integrations/lily_mongodb", default-features = false }
linkme = { version = "0.3", optional = true }
mongodb = "3.8.2"
serde = { version = "1", features = ["derive"] }

[workspace]
