[package]
name = "lily_config"
version = "0.1.0"
edition = "2024"
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[features]
default = []
transactional-inbox-mongodb = []
transactional-inbox-postgresql = []

[dependencies] 
async-trait = { workspace = true }
tokio = { workspace = true }
toml = "0.8"
serde = { workspace = true }
url = "2.5"
lily_injection = { version = "0.1.0", path = "../lily_injection" }
lily_error = { version = "0.1.0", path = "../lily_error" }
