[package]
name = "umbrella-feature-matrix"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
lily = { path = "../../../../crates/lily", default-features = false }

[features]
default = []
consumer = ["lily/consumer"]
http-api = ["lily/http-api"]
websocket = ["lily/websocket"]
websocket-redis = ["lily/websocket-redis"]
clickhouse = ["lily/clickhouse"]
clickhouse-single = ["lily/clickhouse-single"]
clickhouse-factory = ["lily/clickhouse-factory"]
mongodb = ["lily/mongodb"]
mongodb-single = ["lily/mongodb-single"]
mongodb-factory = ["lily/mongodb-factory"]
postgresql = ["lily/postgresql"]
postgresql-single = ["lily/postgresql-single"]
postgresql-factory = ["lily/postgresql-factory"]
queue = ["lily/queue"]
queue-client = ["lily/queue-client"]
queue-client-single = ["lily/queue-client-single"]
queue-client-factory = ["lily/queue-client-factory"]
redis = ["lily/redis"]
redis-single = ["lily/redis-single"]
redis-factory = ["lily/redis-factory"]
trace = ["lily/trace"]
trace-console = ["lily/trace-console"]
config = ["lily/config"]
websocket-client = ["lily/websocket-client"]
websocket-client-single = ["lily/websocket-client-single"]
websocket-client-factory = ["lily/websocket-client-factory"]
injection = ["lily/injection"]
http-client = ["lily/http-client"]
error = ["lily/error"]
background-service = ["lily/background-service"]
cancellation = ["lily/cancellation"]
consumer-asyncapi = ["lily/consumer-asyncapi"]
consumer-fuzzing = ["lily/consumer-fuzzing"]
consumer-transactional-inbox-mongodb = ["lily/consumer-transactional-inbox-mongodb"]
consumer-transactional-inbox-mongodb-factory = ["lily/consumer-transactional-inbox-mongodb-factory"]
consumer-transactional-inbox-postgresql = ["lily/consumer-transactional-inbox-postgresql"]
consumer-transactional-inbox-postgresql-factory = ["lily/consumer-transactional-inbox-postgresql-factory"]
http-api-fuzzing = ["lily/http-api-fuzzing"]
websocket-fuzzing = ["lily/websocket-fuzzing"]
mongodb-factory-api = ["lily/mongodb-factory-api"]
mongodb-test-support = ["lily/mongodb-test-support"]
postgresql-factory-api = ["lily/postgresql-factory-api"]
postgresql-test-support = ["lily/postgresql-test-support"]
queue-asyncapi = ["lily/queue-asyncapi"]
queue-test-support = ["lily/queue-test-support"]
queue-fuzzing = ["lily/queue-fuzzing"]
queue-transactional-inbox-mongodb = ["lily/queue-transactional-inbox-mongodb"]
queue-transactional-inbox-mongodb-factory = ["lily/queue-transactional-inbox-mongodb-factory"]
queue-transactional-inbox-postgresql = ["lily/queue-transactional-inbox-postgresql"]
queue-transactional-inbox-postgresql-factory = ["lily/queue-transactional-inbox-postgresql-factory"]
config-transactional-inbox-mongodb = ["lily/config-transactional-inbox-mongodb"]
config-transactional-inbox-postgresql = ["lily/config-transactional-inbox-postgresql"]
websocket-client-di = ["lily/websocket-client-di"]
error-mongodb-driver = ["lily/error-mongodb-driver"]
